docs/rate-limits.md
The second link to `/docs/staging-environment/` on the rate limit page is missing a leading `/` and 404s.
=> Fix broken staging link

docs/acme-protocol-updates.md
The ACME Protocol Updates page of the documentation described the two
currently implemented ACME versions and indicated each were implementing
draft 01 "with some tweaks".
Since we now have a shiny new ACME Divergences document in the Boulder
repo that describes these tweaks we can link to it directly. This commit
introduces the links.
=> Add link to Boulder's ACME Divergences doc.

docs/faq.md
This reverts commit 943198a180d175a5fe9445caa9c666bf63624d82.
After discussion we don't think this meets the threshold for a *frequently* asked question and it is better suited for the integration guide.
=> Revert "Add a FAQ entry for CSR sigalg support."

docs/integration-guide.md
This commit describes the supported key algorithms for both account keys and certificate keys. In particular it notes the supported ECDSA curves and mentions our recommendation to support both an RSA cert and an ECDSA cert.
=> Add supported key algs to integration guide.

getinvolved.md
We don't actively use this list to coordinate development.
=> Remove reference to ca-dev list.

howitworks.md
The link now links to a doc site and not to a (community) thread (anymore?). So this changes the wording.
=> Change thread to page

getinvolved.md
This is linked in the Certbot README, which will be kept more up-to-date
The IRC channel #certbot we link may not be the best one.
=> Remove reference to Certbot dev IRC.

docs/client-options.md
Correction for the Plesk url - it was pointing to Virtualmin
=> Correct url for Plesk

docs/staging-environment.md
Prior to this PR we do not describe the differences between staging & prod from a rate-limit perspective.
*Note*: Currently the `registrationsPerIP` limit is actually **lower** in staging than in prod. I have documented the current difference while I stage a PR with ops to update the staging environment to use the same value as production. I will update this section of the staging docs when the updated policy is deployed to staging.
Staging:
```
registrationsPerIP:
window: 168h # 1 week
threshold: 100
```
Prod:
```
registrationsPerIP:
window: 3h
threshold: 500
```
=> Add description of the staging env. rate limits.

docs/staging-environment.md
Previously the Registrations Per IP Address limit differed from production and so was described on the staging environment page. Since the staging limit has been changed (IN-799) to match production the staging page needs to be updated to remove the old reg per IP limit.
=> Remove RegPerIP staging limit.

_includes/header.html, about.md, docs/index.md, isrg.md
@bdaehlie Nice start! I think Support / Donate has the same semantic ambiguity as I mentioned in #31, with Contribute / Donate. I've tried another round of iteration, please let me know what you think!
Add top-level links for Get Started, Get Help, and Documentation links.
Move Technology links into the Documentation page.
Move Statistics and Service Status into About menu.
Make Donate and About headings into actual links. This is better for screen
readers, people with JavaScript disabled, and potentially for SEO.
Add links to /about/ to copy what's in the menu.
Move TAB section of /about/ into /isrg/, alongside board member list.
=> Further reorganization.

_sass/_base.scss
On Windows, the font weight of 300 is hard to read, and almost shimmers on big blocks of text.
Does this bother anyone else? Don't want to make it look pudgy on macOS etc., which generally have heavier antialiasing.
Proposed weight of **400**:
Default weight of **300**:
=> Increase base font-weight to 400

docs/client-options.md
I'm proud to say that [Zappa](https://github.com/Miserlou/Zappa) now has extremely tight integration with Let'sEncrypt, allowing AWS Lambda + API Gateway users to have one-command LE installation!
By calling `zappa certify`, Zappa will automatically verify the supplied domain using Route53 for DNS-based challenges, install the new LE Certificate in the API Gateway, and even schedule an AWS Schedule Event Function to renew the certificate automatically on Lambda before it expires!
Incredible stuff, thanks for building and maintaining Let's Encrypt!
=> Adds Zappa to the list of projects integrating with LetsEncrypt

docs/staging-environment.md, howitworks.md
Changes the intro text to describe a little bit about what Let's Encrypt does.
Rename "Choose a Let's Encrypt Client" to "With Shell Access", and add
"Without Shell Access" section.
Consistently use "ACME client" rather than "client."
Part of #59. Viewable at http://leweb.crud.net/getting-started/.
/cc @bdaehlie @pde
=> Describe how to use without shell access.

_includes/footer.html, _includes/head.html, js/ga.js
Move Google Analytics to its own file and load it per guidance:
https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet
This in combination with PR #61 permits the following, much tighter CSP
policy:
> Content-Security-Policy "default-src 'self'; style-src 'unsafe-inline' 'self'; script-src 'unsafe-eval' 'self' https://www.google-analytics.com; img-src 'self' data: https://www.google-analytics.com;"
This can land whenever, but the CSP policy shouldn't be updated until #61 lands.
Additionally, the CSP policy should be updated with care and tested as well as
possible before being left alone.
For reference, the current CSP policy is:
>Content-Security-Policy "default-src 'self' https://letsencrypt.org; style-src 'unsafe-inline' 'self' …
=> Tighten CSP

certificates.md
As the title says the X1 intermediate is retired and the X3 is the new one. This has also a Cross-Signing with IdenTrust so we should make this clear.
=> Cross-signed X1 is retired X3 is the new one

index.html, sponsors.html
A member of the community forum (Hi @jomo!) reported[0] that some of our sponsor links use `http://` for the protocol even though the target server supports `https://`.
This commit updates the following sponsor links to use https:
* Akamai
* Cisco
The following were not updated because they are just HTTPS->HTTP redirects:
* Gemalto
* 3cx
The following were not updated because of errors only present with the HTTPS version (mixed content warnings, 404, etc):
* ALA
* WPBeginner
* Casino2k
* Reliable Site
[0] - https://community.letsencrypt.org/t/some-sponsor-links-on-the-website-are-http/21119
=> Updates some sponsor links to use `https://`.

js/stats.js, stats.md
Use "HTTPS" instead of "Secure."
Add a "%" to y-axis ticks, and expand on y-axis label.
Better link for Telemetry info.
Specify daily updates for data.
cc @jcjones
=> Tweak stats page.

docs/rate-limits.md
An individual in the #letsencrypt IRC channel mentioned that it would have been helpful to find a link to the integration guide somewhere on the rate limits page.
I agree and think it would help make the integration guide more discoverable. Thinking as a large provider/integrator I'm likely to check the rate limits page as one of my first excursions into evaluating Let's Encrypt and familiarizing myself with the documentation.
This PR adds a sentence pointing to the integration guide.
=> Adds a integration guide link to ratelimit page.

docs/client-options.md
It let's you create / renew let's encrypt certificates using temporary Amazon EC2 / Digital Ocean machines.
=> adds a docker option

docs/acme-protocol-updates.md
This PR updates the current ACME version linked from draft-03 to draft-04.
<s>*Note*: This should **not** be merged until https://github.com/letsencrypt/boulder/pull/2356 is merged into
Boulder's master branch to catch the divergences document up to draft-04 as well.</s>
This is all ready to merge. https://github.com/letsencrypt/boulder/pull/2356 landed to master.
=> Updates current ACME draft from 03 to 04.

getinvolved.md
This commit improves the "Get Involved" website page in a few ways. The certbot language is updated, the ACME references are changed to the IETF repos instead of our forks, the Boulder get involved steps are more detailed.
=> Improves the "Get Involved" page.

js/stats.js
User feedback is that:
1) The Percent Secure Connections graph's newest data is getting overlapped by
the toolbar, and
2) The Percent Secure Connections graph Y-range isn't dramatic
This change adds top-margins to all graphs sufficient to avoid overlapping the
data and the data-highlights on several tested platforms. It also re-enables
auto-ranging on the Percent Secure Connections graph.
=> Increase stats graph margins on % Secure Connections

docs/cert-compat.md
https://bugs.openjdk.java.net/browse/JDK-8154757
I tested validating an LE certificate under 7u111 successfully; previous versions failed as expected.
=> added JDK 7u111 compatibility

docs/index.md, docs/integration-guide.md
We see a fair number of repeated validation failures from some hosts. This guidance can help reduce that failed validation volume.
This also adds a link to the new API announcements page on the community forums.
=> Add retry info and API announcements page

docs/client-options.md
Easy to use reverse proxy.
It need zero settings to start (easy for home, vps and so on). Only extract binary from archive and start binary.
It is created for shared hosting (can handle thousands domains).
It is cross platform. Main platforms windows/linux.
=> Add lets-proxy to client options

.gitignore, .travis.yml, Gemfile
This PR adds a `.travis.yml` for doing continuous integration builds of the website. Once builds are running it would be sensible to enable the branch protection that requires a PR have green CI before being merged. This will help keep pull requests from breaking the build accidentally and also gives a starting point that can be extended to run a lint of the website (e.g. to find 404's, broken content).
=> Adds travis ci 

docs/index.md
In https://github.com/letsencrypt/website/pull/102 it looks like we mistakenly [added a new link](https://github.com/letsencrypt/website/pull/102/files#diff-1a523bd9fa0dbf998008b37579210e12) to `index.md` pointing to a "What is a Certificate?" page that wasn't included in the PR.
This PR removes that link - it seems to me like it was accidentally included into #102 but is unrelated.
Thanks to [the community forum](https://community.letsencrypt.org/t/missing-page-on-site/24811) & @viklele for flagging this!
=> Removes 404 link for "What is a Certificate?"

docs/rate-limits.md
This PR documents the overall requests-per-second ratelimits we introduced.
=> Adds overall requests-per-second ratelimits

.travis.yml, Gemfile.ci
Until there are clear instructions for how to get a sane Ruby 2.2+ install on dev machines that will cleanly install the `html-proofer` gem it should only be required for CI.
This PR tells travis to use the `Gemfile.ci` gemfile instead of the default `Gemfile`. Only the `Gemfile.ci` has `html-proofer` included.
=> Only install 'html-proofer' for CI

docs/client-options.md
In #120 I removed the Daplie client/libs from the `client-options.md` page because their entire GH org was 404ing. I assumed they closed their account but it seems like they have migrated to [Gitlab](https://gitlab.com/Daplie) after Github closed their account on [short notice](https://daplie.com/articles/why-github-took-down-daplie/).
I think its fair to restore the links pointing to the new location. I originally removed the links instead of replacing them only because I was unaware of the new location.
=> Restore Daplie clients/libs.

docs/integration-guide.md
This PR updates the integration guide to briefly describe our thoughts on SAN name distribution across certificates.
Should you issue few certificates with many names, or many certificates with few names?
:warning: Read on to find out more! :books:  The answer may shock you. :zap: Hidden secrets of Let's Encrypt certificates finally revealed. :secret: 
(Both strategies are about equal with unique strengths/weaknesses).
=> Adds advice on name distribution across certificates.

docs/cert-compat.md
Based on [a community forum thread](https://community.letsencrypt.org/t/windows-live-mail-revocation-warning/26310) it appears Windows Live Mail (the discontinued, 2002 era "freeware" mail client) is not compatible with Let's Encrypt certificates because we do not maintain a CRL for end entity certificates.
=> Adds Windows Live Mail to incompat list

docs/rate-limits.md
User 'tjs' [found](https://community.letsencrypt.org/t/is-the-recently-announced-failed-validation-limit-effective/27806) an error in the Failed Validation announcement. It says February 2016 when the announcement was made after that date. Ergo, it should be 2017 :P
=> Fix year in Faild Validation announcement

docs/client-options.md
The `test/js/test.js` client from the Boulder repo was removed in https://github.com/letsencrypt/boulder/pull/2549
The Website CI caught this broken link :tada:
=> Removes Boulder `test.js` client from client-options.

.travis.yml, Rakefile
This PR removes most of the exceptions from the htmlproofer
Rakefile.
The failures that were fixed are in three categories:
1. Sites that timed-out with the base timeout. This was fixed by
increasing the Typheous timeout to 15s
2. Sites that had chained up to Identrust's root CA cert
3. Sites that required TLS 1.2+
Items 2 and 3 were fixed by updating the project .travis.yml to add
`sudo: required`. Nothing in our CI pipeline truly requires `sudo` but
this flag is used to gate whether the Ruby build image is Ubuntu 12.04
or 14.04.
One exception remains for `crates.io`. The only workaround I could
identify to fix that false-positive created additional failures with
other sites so I gave up for now.
Resolves https://github.com/letsencrypt/website/issues/134
=> Tightens up CI for htmlproofer.

Rakefile
Presently the client-options page links to "https://www.froxlor.org",
which has a certificate hostname mismatch. "http://froxlor.org"
indicates they're having a major outage so for now their URL is added to
the :url_ignore list.
=> Adds `www.froxlor.org` to the `:url_ignore` list for CI.

docs/client-options.md
ZeroSSL Docker image (Lightweight Alpine-based, non-root process)
=> New Docker client added

docs/client-options.md
https://github.com/letsencrypt/website/pull/150 had broken markdown formatting and I failed to notice. This commit fixes the markdown.
=> Fixes markdown error for autocert.

docs/client-options.md
The [pfSense](https://www.pfsense.org) OSS firewall project has an [ACME package](https://doc.pfsense.org/index.php/ACME_package) to manage Let's Encrypt certificates for its GUI and other purposes, so it would be helpful to add it to the list of projects integrating with LE.
=> Add pfSense to the list of Projects integrating with Let's Encrypt

Rakefile
This commit removes `www.froxlor.org` from the ignore list for the
website linting. Previously there was a hostname mismatch error that
has since been resolved.
This commit also adds `www.ICANN.org` to the ignore list. It's always
timing out in CI and I'm not sure why, seems to work fine when I test
manually. Similarly `www.vtex.com` is suffering a DNS failure but only
in CI so I'm adding it to the ignore list.
=> Remove froxlor from urlcheck ignore, add ICANN.org

docs/client-options.md
Just came across this page that mentions various products that support LE. Cloudron is a platform for installing apps on your server. Idea is you setup the server with a domain foo.com and install apps into app1.foo.com, app2.foo.com and so on. LE was god-send for us since we could now gets certs programmatically for each of the domains. We integrated LE more than a year ago  (https://git.cloudron.io/cloudron/box/commits/master/src/cert/acme.js). The code also supports testing against LE staging and prod.
Thanks for this amazing project!
=> Add Cloudron to client options

docs/rate-limits.md
This updates the information regarding rate limiting for /acme and /directory and removes references to the overall rate limit which no longer exists. I'm not sure I love having "/acme" start a sentence, so I'm open to suggested edits.
=> update nginx rate limit details

docs/faq.md
The only cached validations currently in the system are 30-day ones, so the old
language is confusing.
Related to #146.
=> Remove mention of 10-month cached validations

docs/staging-environment.md
This PR updates the staging rate limit documentation to mention the higher 50 accounts per IP per 3 hour limit.
=> Update staging rate limits docs for Accounts per IP.

docs/client-options.md
- I added a new listing for a new python based letsencrypt client
- I created the [sewer](https://github.com/komuW/sewer) letsencrypt client since I was unable to find one that is primarily meant to be used as a python libarary (as opposed to a commandline app)
=> added a new python letsencrypt client

docs/rate-limits.md
The order of renewals & new certificate issuance operations are no
longer a factor in the renewal exemption calculation. This commit
updates the rate-limit documentation accordingly.
=> Update the rate-limit documentation to remove renewal order advice.

upcoming-features.md
https://github.com/letsencrypt/boulder/issues/2244#issuecomment-260044452
> That said, we are starting to design the process to submit precertificates so we can embed SCTs in certificates, and plan to implement before next October.
https://community.letsencrypt.org/t/le-embed-sct-support-policy/36471/2
> Our plan has not changed as far as I'm aware. Thanks!
=> Embed SCT receipts in certificates: October, 2017

upcoming-features.md
It looks like commit e3dfd53525a6d2cb32839cf06ebbd85cb61b0b2c didn't update years. I assume 2018 is right.
=> Correct upcoming features to not have future functionality in the past.

_includes/head.html
Previously we were setting a meta description tag for all pages that contained
the generic description "Let's Encrypt is a free, automated, and open certificate
authority brought to you by the non-profit Internet Security Research Group
(ISRG)." This gets inserted, e.g. into summaries of links pasted in
Discourse, which is confusing, because it makes it look as if the link goes to
the homepage.
In this change, only provide the default description for the homepage.
=> Only give site description on homepage.

docs/caa.md
I have new URLs for the generator and DNS provider support pages.  There's an HTTP redirect in place from the old URL, but that doesn't help with the anchor link.
=> Update links to SSLMate's CAA record page

util/linkcheckerrc
It seems like `https://www.ietf.org/mailman/listinfo/acme` continually
returns a 503 recently. Loading in the browser I see there is
a Cloudflare interstitial and I suspect Cloudflare's annoying bot
fingerprinting crap is blocking the test connections. This commit adds
`www.ietf.org` to the ignore list to work around this.
=> Ignore `www.ietf.org` in CI linkcheck.

docs/client-options.md
The link to the "Daplie" project linked under "Projects Integrating with
LE" now 404s. Looking at the daplie.com website it's not clear what
happened to the "Walnut" or whether they still integrate with LE. I'm
going to remove the link for now and if someone can provide the correct
link and assurance the project still integrates with LE it can be
readded.
Fixes CI.
=> Removes `Daplie` from "Projects Integrating with LE" list.

index.html, sponsors.html
Some sponsors has a valid https configuration but linked with no-https.
updated:
- `https://www.internetsociety.org/`
- `https://www.3cx.com/`
- `https://www.vtex.com/`
- `https://www.fordfound.org/`
=> https instead http for sponsors url

docs/caa.md
We have received permission from the various root programs to switch off
the legacy CAA so this docs page no longer needs a link to the legacy
CAA API announcement.
_Note: This change isn't active in production yet. Just staging a website update to be ready_.
=> Remove note about legacy CAA.

docs/client-options.md
It appears as though [Aegir](http://www.aegirproject.org/) is missing from the list of projects that integrate with Let's Encrypt.  Here's the list item to add it.
=> Add Aegir to the list of project integrations

docs/caa.md
Our description of CAA tree-climbing was written when its status was still in flux. Now that it's settled, use simpler language to describe it.
=> Simplify language around tree-climing

docs/client-options.md
The official name of https://github.com/hlandau/acme appears to be "acmetool", all lower case. Update its entry to match.
=> Client Implementations: Fix acmetool name

docs/client-options.md
ACMEproxy is a dns-01 challenge backend for PowerDNS with an HTTPS API for publishing challenges.
=> Adds ACMEproxy to the Python list

docs/client-options.md
[acme.sh added support in the "2" branch](https://community.letsencrypt.org/t/acme-sh-supports-acme-v2-wildcard-now/49685). ACME4J [merged support to master](https://twitter.com/shred_/status/950040298176110592) and cut a new release.
=> v2 compat: Add acme.sh, update ACME4J

docs/account-id.md
The account ID is being sent in the "Boulder-Requester" header, as added in https://github.com/letsencrypt/boulder/pull/1886.
=> Update header name on Account ID page

layouts/_default/rss.xml
Hugo is adding one, which makes two.
=> Remove superfluous XML header in RSS feed

content/stats.md
Now updated, the `/stats` page indicates the standard Mozilla Telemetry documentation as the source of our HTTPS Ratio statistics; that is misleading. Since Firefox 58's telemetry changeover, that source is [now a separate dataset](https://github.com/mozilla/firefox-data-docs/pull/80).
This change updates the documentation to refer to the new data set descriptor. It also fixes a markdown list bug that appears to have come through from the switch to hugo, where the list at the bottom of `/stats` wasn't showing as a list any more.
**NOTE:** This change should not be merged until the link https://docs.telemetry.mozilla.org/datasets/other/ssl/reference.html is live.
=> Update the links to Mozilla's Telemetry, and also fix the /stats/ markdown list

content/docs/client-options.md
Hey Let's Encrypt!
I propose to add [Traefik](https://github.com/containous/traefik) to Let's Encrypt's clients in the documentation.
Keep up the good work 👍
=> Add Traefik to clients

content/docs/client-options.md
Added Hiawatha's Let's Encrypt script to the ACME v2 Compatible Clients section.
Updated link of Hiawatha's Let's Encrypt script in PHP section.
=> Hiawatha's Let's Encrypt script

content/docs/client-options.md
dehydrated supports ACMEv2 in its current git master branch
=> added dehydrated to list of acmev2 compatible client-options

content/docs/client-options.md
The ACME v2 link to ame.sh is broken. It was a link to the client's v2 branch; now the branch has been merged into master and deleted, so the link no longer works. Change it link to master.
Reported by rleeden on the [forum](https://community.letsencrypt.org/t/acme-client-implementations-404-on-acme-sh-link/53596).
Unrelated: Remove an extra "/" from a different URL.
=> client-options.md: Fix acme.sh ACME v2 link

content/docs/client-options.md
This client was previously listed in this position under
"letsencrypt-win-simple" and was removed for infringing the Let's
Encrypt trademark. It has since been renamed :tada: so we can add it
back to the spot it was in before :-)
=> Add win-acme to the client options list.

content/docs/client-options.md
letsencrypt-rs removed from client-options in f565f26de2b61a0cf4660c716a89cb2dfdef8722 due to ISRG trademark violation. This issue is [fixed](https://github.com/onur/acme-client/issues/25) and letsencrypt-rs is renamed to acme-client now.
This patch adds acme-client to client-options.
=> Add Rust acme-client library

content/docs/client-options.md
Synchronet just got an ACMEv2 client (LetSyncrypt)... code here: http://cvs.synchro.net/cgi-bin/viewcvs.cgi/exec/letsyncrypt.js and here: http://cvs.synchro.net/cgi-bin/viewcvs.cgi/exec/load/acmev2.js
=> Add Synchronet SBBS, which now has an ACMEv2 client included.

content/docs/client-options.md
- added sewer to list of clients that support acme version 2
- v2 is the future 
- fulfill this call to action; https://community.letsencrypt.org/t/staging-endpoint-for-acme-v2/49605
=> add sewer to acme v2 supporting clients

content/docs/client-options.md
added stonemax/acme2 (PHP Client) to list of clients that support acme version 2
* v2 is the future
* fulfill this call to action; https://community.letsencrypt.org/t/staging-endpoint-for-acme-v2/49605
=> stonemax/acme2(PHP client for acme2)

content/docs/client-options.md
Adding Crypt::LE to the list of ACME v2 compatible clients (perhaps the list should be sorted alphabetically as well, to look a bit less "chaotic" and easier to browse).
=> Added Crypt::LE to ACME v2 list.

content/docs/client-options.md
The node.js library 'greenlock' and related clients seem to have moved to a different git server.
=> Greenlock seems to have moved

layouts/partials/head.html
This should lower the overhead of dns lookups on these external resources (see https://css-tricks.com/prefetching-preloading-prebrowsing/)
=> dns-prefetch google analytics and google ads

content/docs/client-options.md
Should I alphabetize this list while I'm at it?
=> Add Caddy to list of ACMEv2-compatible clients

content/docs/client-options.md
Certify SSL Manager on Windows now has ACME v2 compat from v4 alpha onwards.
=> Update title and ACME v2 compat for Certify (The Web)

content/en/docs/staging-environment.md
Request:
can you change the github repo description from "Let's Encrypt Website"
to "Let's Encrypt Website **and documentation**" ?
I was clicking too fast; went to github, but `^f` didn't find any `docs`, 
so I went back to forums to search for documentation .. eventually back to github and found it.
=> Fix typo:  "three 3" -> "3"

content/en/docs/client-options.md
This is a v2 based PowerShell client installable from the [PowerShell Gallery](https://www.powershellgallery.com/packages/Posh-ACME/1.1).
=> Add Posh-ACME to v2 and Windows client lists

content/en/docs/client-options.md
acme-dns-tiny is a fork of acme-tiny project to provide a Python 3 script able to respond to `dns-01` challenges with automatic DNS updates (by use of a TSIG key).
This week the project has released it's `v2.0` version which is compatible with ACME draft-09 (Let's Encrypt API v2).
=> add acme-dns-tiny to client options

content/en/docs/client-options.md
The sponsorship for Greenlock has changed and the prior company has asked me to remove references to them.
Also, it has been updated for v2.
=> Update Greenlock branding

content/en/docs/client-options.md
Fixed https://github.com/diafygi/acme-nosudo/issues/98
=> added back acme-nosudo client (renamed from letsencrypt-nosudo)

content/en/docs/client-options.md
Adding eggsampler/acme to clientoptions.md under v2 and Go headings.
=> Add eggsampler/acme to v2 and Go client options

content/en/technicaloverview.md
in the sentence:
> If so, it publishes revocation information into the normal revocation channels
`It` refers to Let's Encrypt, and not any ACME CA, and as Let's Encrypt only uses OCSP, and not CRLs, I think it should at least not be mentioned.
(the image howitworks_revocation.png should probably be updated too, or the text should mentioned that Let's Encrypt doesn't uses CRLs)
=> Let's Encrypt uses OCSP only, not CRLs

content/en/docs/client-options.md
The client has ACME v2 support since Ansible 2.5.1. It works fine both with the staging server as well as with the production endpoint.
I've added a link to the documentation on the `letsencrypt` module for Ansible.
=> Ansible's acme_certificate client

content/en/docs/client-options.md
Please consider pulling this commit with links to the new (official) ACME v2 client for HAProxy.
=> HAProxy ACME v2 client

content/en/docs/client-options.md
PJAC version >= 3.0.0 now compatible with ACME version 2.
https://github.com/porunov/acme_client
=> Add PJAC to ACME v2 compatible clients

content/en/docs/rate-limits.md
This calculation is out of date; it presume the certs per registered domain per week limit is the old value of 20; the commit 7ea2fa0f1c3db2679d52be3c5f109961ffdeb25b
> commit 7ea2fa0f1c3db2679d52be3c5f109961ffdeb25b
> Author: Josh Aas <jaas@kflag.net>
> Date:   Wed Aug 1 15:40:37 2018 -0500
>
> Certs per domain per week rate limit has been raised to 50.
updated the certs per registered domain per week limit, but forgot to update this dependent calculation.
Closes #360.
=> Correct error in unique subdomains per week

content/en/docs/client-options.md
Add WinCertes ACMEv2 Client for Windows, based on Certes library.
=> Adding WinCertes client

content/en/certificates.md
Thanks to @tdelmas for flagging this outdated reference to the "official Let's Encrypt software".
Resolves https://github.com/letsencrypt/website/issues/372
=> Certificates: correct Certbot ref

content/en/certificates.md
Sorry @cpu to didn't see it in #375 before it was merged
=> Fix inversion in the link between "https://certbot.org" and "Certbot"

content/en/docs/client-options.md
Add instructions about sending a PR to update the client-options page. Specifically mention where to add your client, and the trademark policy.
After internal discussion we've determined that browser based clients do not provide the ACME experience we want to prioritize with our client options page. This commit removes all of the browser based clients and
updates the page to describe this policy.
=> client-options: document inclusion/update policy.

layouts/partials/head.html
Pages can use the "description" attribute to fill them.
Cf https://github.com/letsencrypt/website/issues/356
=> The meta description now matches the meta twitter:description

content/en/docs/client-options.md
Perhaps it is the first 3rd party client that does complete automation, including SSL certificate installation, in shared hosting cPanel. No root access required.
It works with Live ACME V2 and V1 API. It is possible to install the client and configure with a browser. Developed for less tech-savvy users.
=> Please add 'FreeSSL.tech Auto' PHP client

layouts/partials/header.html, src/css/_nav.scss, static/css/main.css, static/js/main.js
Closes #379
- Removes use of the `.isOpen` selector in favour of using `.pure-menu-active` only
- Left-aligns nav menu text for better readability and consistency across small & large screens
- Simplifies small-screen menu to use default positioning, instead of absolute.
- Adds a bunch of variables for CSS class names & selectors
- Change handling of the ESC key & clicking out-of-bounds to close the entire navigation menu rather than closing only the current sub-menu. 
Tested on:
- Chrome Version 69.0.3497.100 (Mac OSX and Android)
- Safari Version 12.0
- Firefox Quantum 61.0
Small-screen mouse navigation:
Small-screen keyboard navigation:
Large-screen mouse navigation:
Large-screen keyboard navigation:
Note that there's a small edge-case bug with the current implementation that has not …
=> Fix dropdown navigation on small screens

config.toml
Following the discussion of https://community.letsencrypt.org/t/help-in-specific-language/74930
=> "Get help" (Obtenir de l'aide) directly point to the French help category

content/en/documents/ISRG-CPS-v2.4.html
(The parenthesis was inside the href)
=> Fix broken link to https://letsencrypt.org/repository/

content/en/docs/client-options.md
And make it reliable for future versions:
https://www.powershellgallery.com/packages/GetSSL-LetsEncrypt/1.4.3/DisplayScript -> https://www.powershellgallery.com/packages/GetSSL-LetsEncrypt/
(that currently redirects to https://www.powershellgallery.com/packages/GetSSL-LetsEncrypt/1.4.7 )
Ping the original commiter @bdaehlie https://github.com/letsencrypt/website/commit/f9bd51dfa41d6bad97db41f7b554af41efbe3988
=> Fix link to GetSSL - Azure Automation

layouts/_default/baseof.html, layouts/_default/blank.html, layouts/post/baseof.html
Set the "lang" attribute to the correct value depending of `languageCode` from https://github.com/letsencrypt/website/blob/master/config.toml
Before: `en`
After: `en-us`, `fr-fr`, `es-us`, ...
=>  Fix i18n <html lang="en"> 

TRANSLATION.md, layouts/shortcodes/lastmod.html
I think I forgot to remove that part when I added the one about `docs/_index.md`, sorry. I see no reason anymore not to translate the documentation.
=> \docs\ can be translated

.travis.yml, config.toml, layouts/index.html
This commit merges in missing blog post translations on the home page from the first site, i.e. English.
To get "first" to mean English, this commit also sets a distinct weight for each language to get the expected sort order (1. English 2. French 3. Spanish).
Note that the links to the blog articles in another language will go to the English version of the site, so you may want to make them open in another window to make that explicit.
Fixes #402
=> Show English blog posts on translated versions

content/en/getinvolved.md, content/es/docs/_index.md, content/es/getinvolved.md, content/es/upcoming-features.md
I also fixed a missing punctuation mark in the English page for `getinvolved.md`. Hope that's not too much, I'll revert the change if it's not needed.
=> i18n Es: Emphasis on the fact that they can help improve the website and its translations

content/en/docs/staging-environment.md
When you use `--staging`, Certbot basically works the same way as it does when using the production server. There are a couple very basic sanity checks around things like changing a certificate lineage from production to staging certs, but for the most part, Certbot treats this server like any other ACME server. This can result in things like staging certificates installed into someone's Apache or Nginx config.
I think a better option for people to use here is `--dry-run` which doesn't allow users to test certificate installation (which isn't affected by the choice of ACME server anyway), but works for the `certonly` and `renew` subcommands and doesn't save the resulting untrusted certificates to disk.
On the Certbot side, we never tell anyone to use `--staging` and always recommend they …
=> Don't tell people to use --staging.

content/en/docs/challenge-types.md
* Mention that multiple validation requests may be made. This isn't true in prod (just staging) but the more people are aware of this being the eventual new normal the better.
* Mention that HTTP-01 redirects to bare IP addresses are forbidden.
=> docs: chall types - mention multiva, no HTTP-01 IP redir.

content/en/post/2017-10-17-acme-support-in-apache-httpd.markdown
Use "https://www.youtube-nocookie.com/embed/..." instead of "https://www.youtube-nocookie.com/embed/..." for the iframe src.
See "Turn on privacy-enhanced mode" on https://support.google.com/youtube/answer/171780?hl=en
IMPORTANT: do NOT merge this PR before adding in the CSP frame-src "https://www.youtube-nocookie.com" after "https://www.youtube.com"
=> Use Youtube privacy-enhanced mode

content/en/docs/client-options.md
Since WildFly 14, it is possible to obtain and manage certificates from Let's Encrypt using the WildFly CLI.
=> client-options: Add WildFly Application Server to the projects integrating with Let's Encrypt

content/en/docs/rate-limits.md
See
https://community.letsencrypt.org/t/rate-limits-fixing-certs-per-name-rate-limit-order-of-operations-gotcha/88189
I think there's room for changing the way we describe the renewal rate limit exception but I wanted to remove the inaccurate note before diving into a larger update later on.
=> docs: update rate limits page RE: renewal ordering.

content/en/docs/rate-limits.md
I updated `docs/rate-limits.md` on March 8th to [remove the rate limit ordering gotcha](https://github.com/letsencrypt/website/commit/061a584f108d674eca805f427618adc47b15557e) and forgot to patch the `lastmod` date.
=> docs: fix rate-limits lastmod date.

content/de/docs/staging-environment.md, content/en/docs/staging-environment.md, content/es/docs/staging-environment.md
> If you're using Certbot, you can use our staging environment with the `--dry-run` flag. For other ACME clients, please read their instructions for information on testing with our staging environment.
This sentence was written twice in `staging-environment.md`.
=> Remove documentation about the old-style staging URL

content/en/docs/expiration-emails.md
Certbot has deprecated `register --update-registration` since ~0.30.0: https://github.com/certbot/certbot/commit/f137d55b31c022e9e574b1d48edc55938048ae21
The new method is to use the dedicated `update_account` command verb.
=> docs: update expiration-emails email change cmd.

content/de/docs/client-options.md
A sentence at the bottom of the clients-option page reads in english:
> Your client is not browser-based and supports automatic renewals.
The german translation misses the negation:
> Ihr Client ist Browser-basiert und unterstützt automatische Erneuerung.
This should be changed to *Ihr Client ist **nicht** Browser-basiert...*
=> Fix missing negation in german translation

content/de/docs/client-options.md, content/en/docs/client-options.md
Lego migrated to the go-acme organization.
https://github.com/xenolf/lego -> https://github.com/go-acme/lego
=> Update lego links.

content/en/docs/ct-logs.html
A press release used an incorrect link to our site.
This will enable that to work too.
=> Add redirect for ct-logs

content/de/docs/_index.md, content/es/docs/_index.md, content/fr/docs/_index.md, content/pt-br/docs/_index.md, content/ru/docs/_index.md
* [Best Practice - Keep Port 80 Open](/docs/allow-port-80/)
* [Challenge Types](/docs/challenge-types/)
* [Certificate Transparency (CT) Logs](/docs/ct-logs/)
=> i18n:  Missing entries in docs index 

content/en/docs/client-options.md
Even though PR https://github.com/letsencrypt/website/pull/519 has been merged, the new client, certman-operator added in PR is not showing up on the website yet and could be because the lastmod was not updated in that PR. So I am submitting this new PR to update the lastmod for the client-options.md page.
Signed-off-by: Tejas Parikh <tparikh@redhat.com>
=> Update the lastmod timestamp for client-options.md

content/de/docs/client-options.md, data/clients.json
To detect not up-to-date translations, translations must have the date set to the English version they correspond to.
(update lastmod on the json file this time only)
=>  Sync lastmod with the English version

content/en/i18n.md, layouts/shortcodes/i18n_status.html
To help following translation and page updates.
Note: the "Github history" link does NOT work with hugo 41, but with hugo 55.
(This can be merged without upgrading hugo now, the rest works fine)
=> Translation status page

content/en/upcoming-features.md
I wonder where the link should point to:
https://letsencrypt.org/docs/ct-logs/ (currently in this PR)
or https://letsencrypt.org/2019/05/15/introducing-oak-ct-log.html
?
=> upcoming-features : CT log enabled

layouts/partials/footer.html, layouts/partials/head.html, static/js/ga.js
There are no reasonable needs to slow the page loading for analytics purpose.
Enabling IP anonymization is better for privacy and have negligible drawbacks.
(If IP anonymization is already enabled in the Google Analytics console, that will just confirm the pledge to respect users privacy)
Cf. #107 and #324
Cf. https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization and https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#aip
=> Defer loading of Google Analytics and enable IP anonymization

layouts/shortcodes/clients.html
It appears that when the Client Options page was changed to be a shortcode, the automatically generated header anchors were lost.
IMO these were useful to have because the page is very long. For example, when linking somebody to Windows clients.
This commit restores the anchors for client and library categories, although unfortunately they do not exactly match the anchors that were there previously.
=> client-options: anchors for client/lib categories

data/clients.json
Additionally remove `acme_v2`, which I assume is reserved for actual clients and not libraries. 
Though I notice that quite a few of the `acme_v2` projects are not actually clients. Maybe there could be a separate PR to clean those up at some point. Otherwise visitors might suffer frustration.
cc @eggsampler to approve
=> client-options: eggsampler/acme is lib, not client

content/de/stats.md, content/en/stats.md, content/es/stats.md, content/fr/stats.md, content/ru/stats.md
The Mozilla telemetry data is incorrect and producing a graph that stops around 2016. We should not show bad data while we sort it out.
=> Remove graphs because the data source is incorrect

content/de/stats.md, content/en/stats.md, content/es/stats.md, content/fr/stats.md, content/ru/stats.md
Reverts letsencrypt/website#575
The data is fixed and renders correctly so we can start showing these graphs again.
An issue has also been created to backup the data file on the website host in case the nightly download has errors.
=> Revert "Remove graphs because the data source is incorrect"

content/en/docs/account-id.md
Updated the "Finding Account IDs" page (English content only) so that:
1) it includes both an ACME v2 and an ACME v1 account URL.
2) it doesn't reference the "shorthand" numeric form. Using only the full URL will help encourage RFC 8555 compatibility.
=> docs: update account-id page, remove shorthand.

layouts/index.html, layouts/partials/head.html
So it's the same link for all languages, and they don't point anymore to an empty feed as blog posts are not translated
Fix #407
nb: use the `dict` syntax to create an object with the `Permalink` attribute to avoid updating translations and allow a easy revert.
=> Hardcode the link to the RSS feed to /feed.xml

data/clients.json
ACME v2 support was added in the v0.13.0 release: https://github.com/GUI/lua-resty-auto-ssl/releases/tag/v0.13.0
=> Update lua-resty-auto-ssl client with ACME v2 supported versions

data/clients.json
So they are still listed.
Also remove the Certbot client (present inline in the template)
=> Adds "library" or "category" for clients with only the acme_v2 flag.

data/clients.json, layouts/shortcodes/clients.html
The client from #582 had the acme_v2 flag and the "Lua" category, but because that category wasn't defined, when the ACME V2 section was removed, the client disappeared. This PR add the `Lua` category and force a build to fail if the category is unknown, the section is unknown, or one none of the two are given.
=> Fix Lua category and add tests

data/clients.json
Looks like lua-resty-acme started a trend of adding client description one-liner as a comments in clients list, which can be seen e.g. at the end here:
https://letsencrypt.org/docs/client-options/#clients-python
This doesn't seem to be the intended use of this field, but when adding new client to the list there, people tend to copy last item's format, and that's how these will probably continue to creep-in.
(was guilty of adding last such comment myself in #682)
IMO original use of this field for only relevant distinguishing features is a much better fit, as everything else can be found on the project page.
This commit removes such comments from last few projects, to clean up the misuse and so that anyone else adding projects to the end will have a proper example to follow.
Thanks!
=> Remove unnecessary description comments from ACME Client list

data/clients.json
`golang.org/x/crypto/acme` now implements ACME v2 and should not be in gray anymore on the website
see: https://github.com/golang/go/issues/21081
cc @x1ddos @bradfitz
thanks!
=> clients.json: update acme_v2 compatibility for golang.org/x/crypto/acme

config/_default/languages.toml
These get re-quoted on HTML generation, providing wrong results.
Fixes #705
=> Don't quote HTML entities in languages.toml.

data/clients.json
OpenBSD's acme-client lives in OpenBSD main source.
It supports ACMEv2.
The old project website is outdated and no longer
maintained.
=> Update OpenBSD acme-client

data/clients.json
Crypt::LE and ZeroSSL were wrongly flagged as not supporting ACME v2 when acme_v2 flag was introduced it seems. Setting that, so they would be misleadingly looking as outdated on the list.
=> Updating v2 flags for Crypt::LE and ZeroSSL Docker.

data/clients.json
=> Fix #722 : update library_url for Go client acmetool

content/de/jobs/_index.md, content/es/jobs/_index.md, content/fr/jobs/_index.md, content/ko/jobs/_index.md, content/ru/jobs/_index.md
I think that alias is useless (except in English). Cf #497 for history
=> Remove the /jobs alias in translations

content/en/getinvolved.md
Since the protocol is done, there's no reason to encourage people to
contribute to its development.
=> Remove ACME from "Getting Involved."

data/clients.json
=> DelphiACME do support V2

content/en/docs/client-options.md, data/clients.json, layouts/shortcodes/clients.html
Now that account creation is disabled, it doesn't make sense to
recommend a v1 client to any new users.
Tidied up the description of the Python acme module.
Removed the note to developers about submitting edits for upgrades to
v2. We have a footer with instructions on adding clients. I added an
ACMEv2 mention there.
Removed "v2" language from client comments. Since all displayed
comments now support ACMEv2, it would be confusing for only
some clients to mention it.
Add a heading section addressing ACMEv1 deprecation.
=> Show only ACMEv2 clients on client-options.

content/en/docs/faq.md
The FAQ page was updated via https://github.com/letsencrypt/website/pull/764 but the lastmod date still says 2017.
=> Update FAQ page lastmod date

data/clients.json
I updated the code to use the V2 endpoint. From looking at the source, this change will end up updating the website somehow. If that's not the case please point me at what I should be changing.
=> Update acme-lw library to V2

layouts/partials/footer.html
Even though San Francisco is a world-famous city and letters probably
will be delivered anyway, include the country "USA" in the address so
that people outside USA can easier send properly addressed letters.
Within USA it hopefully doesn't hurt to state the country as well.
Also move some comma separators outside of the schema defined fields
since they're not part of the field.
=> Add country to ISRG address in footer

content/en/docs/faq.md, content/ru/docs/faq.md, content/sv/docs/faq.md
The URL https://www.google.com/safebrowsing/report_badware/ is used in
the FAQ but it redirects to
https://safebrowsing.google.com/safebrowsing/report_badware/ nowadays.
Change the URL to save the visitor a redirect.
Also escape the underscore in the URL since that's proper Markdown (vim
marks it with red otherwise).
Update all up-to-date translations to avoid unnecessary warnings about
out-of-date translation.
=> FAQ: New Google Safe Browsing URL

netlify.toml
Docs: https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify
I tested that it correctly override the  HUGO_VERSION specified in the "Environment variables" of the Netlify config.
It think it's better to specify it here (than in https://app.netlify.com/sites/XXX/settings/deploys) so a simple PR can upgrade it's version, and it's publicly documented.
=> Use netlify.toml to specify Hugo version

layouts/shortcodes/docs_index.md
The link to the blog post about onboarding customers with Let's Encrypt
and ACME in the documentation index doesn't work using "hugo server -F"
(Hugo v0.59.1), but it works on the live site and on Netlify pull
request previews.
Add the missing .html suffix to the link in order to make it work
locally as well.
=> Doc index: Add .html suffix to link to blog post

content/sv/docs/rate-limits.md, content/sv/getting-started.md
Also change the translation of "rate limit" on the Getting Started page
to match the word used on the Rate Limits page (before it was translated
to speed limit rather than rate limit).
=> Swedish translation of Rate Limits

.travis.yml, config/_default/config.toml, netlify.toml
- Keeps blackFriday as the markdown parser (goldmark is the new default since hugo 60, and the .md pages are not currently compatible with it and the `id` generation algorithm is different from § name)
- Keeps code highlight = false (true is the new default since hugo 60 but it has an escaping bug with blackFriday)
Tested with netlify: Hugo 62 is supported.
The diff is:
- Hugo version in meta/rss (of course)
- Insignificant whitespace
- In sitemaps `<priority>0</priority>` is added
Full diff:
```diff
diff -r 55.6/de/feed.xml 62.0/de/feed.xml
10c10
<     <generator>Hugo v0.55.6</generator>
---
>     <generator>Hugo v0.62.0</generator>
diff -r 55.6/de/index.html 62.0/de/index.html
7c7
< 	<meta name="generator" content="Hugo 0.55.6" />
---
> 	<meta name="generator" content="Hugo 0.62.0" /> …
```
=> Update to Hugo 62

data/clients.json
ACME v2 support since https://github.com/hlandau/acmetool/releases/tag/v0.2.1
Also, homepage URL change
=> acmetool ACMEv2 support

content/en/_headers, content/en/repository.md
The CPA of Canada requires a referral header to be sent to allow access to the newest Webtrust audit seals.
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
I should be able to click on the following links in the repository and see the seals.
* August 31, 2019: https://www.cpacanada.ca/webtrustseal?sealid=10336
* August 31, 2019: https://www.cpacanada.ca/webtrustseal?sealid=10337
Testing
```
curl -I --referer https://letsencrypt.org https://www.cpacanada.ca/webtrustseal?sealid=10336
curl -I --referer https://letsencrypt.org https://www.cpacanada.ca/webtrustseal?sealid=10337
```
=> Add referral header when navigating to Webtrust seals

layouts/partials/header.html
When on a page that can be translated (not a blog page), the menu stays on that page, only change the lang. On other pages, it goes to the home of the selected language.
=> The lang select menu stays on the same page

content/en/getting-started.md
Linking to https://ietf-wg-acme.github.io/acme/ isn't a very friendly experience. It's a landing page with a bunch of links and no clarity on which should be used.
E.g., Is it the link for ["Preview for branch omfg-make-it-stop"](https://ietf-wg-acme.github.io/acme/omfg-make-it-stop) ? (lol)
A link directly to RFC 8555 seems like a better choice.
=> content: getting-started pg, link ACME to RFC 8555.

data/clients.json
https://community.letsencrypt.org/t/lua-resty-acme-0-5-0-release-native-tls-alpn-01-challenge-handler-for-nginx-openresty/112704
=> Lua-resty-acme 0.5.0 release: native tls-alpn-01 challenge handler for Nginx/Openresty

layouts/_default/single.html
For not-yet-translated page, fix url rewriting with anchor: now, in FR  it does find "href="/repository/#isrg-certificate-policy" to rewrite into "href="/fr/repository/#isrg-certificate-policy" for example.
Tested with a full html diff. Fix two links in glossary for fr,id,ja,pt-br,ru,sr,sv,vi
Now those links correctly go to the not translated page `repository` of the current language instead of going back into the English page of `repository`
Also remove unnecessary whitespaces.
=> Fix url rewrite with anchors

layouts/partials/header.html
When viewed in safari hamburger menu, the language
menu item doesn't work. Adding a tabindex fixes it.
Fixes #913
=> Add tabindex to language menu item.

.travis.yml, DOCUMENTATION.md, netlify.toml
And adds some documentation.
The diff between hugo 0.62.0 and 0.64.1 is empty (not even whitespace!), only the version changes.
=> Update to hugo 0.64.1

content/en/repository.html
A few pages use them:
https://letsencrypt.org/repository/#isrg-certification-practice-statement
https://letsencrypt.org/repository/#isrg-certificate-policy
They disappeared with the md=>html conversion https://github.com/letsencrypt/website/commit/da125f66f762bb6fd15746eec5a623277cfcd8f4
=> Fix repository anchors

content/de/trademarks.md, content/en/trademarks.md, content/es/trademarks.md, content/ko/trademarks.md
Fix  #963
In https://letsencrypt.org/trademarks/ there is press[at]letsencrypt.org (to avoid spam I guess) but two lines after there is a real mailto: link to that email. I think it will be better to just always use the mailto:
=> Real email instead of [at]

content/en/_headers, content/en/repository.html
Fix #975
> strict-origin
Only send the origin of the document as the referrer when the protocol security level stays the same (HTTPS→HTTPS), but don't send it to a less secure destination (HTTPS→HTTP).
=> Referrer-Policy: strict-origin for repository

layouts/shortcodes/ct_logs.html, src/css/_base.scss
Cf https://github.com/tdelmas/website/pull/32
The current shortcode generate the following html:
```html
<ul>
<li>explanation...</li>
<li>explanation...</li>
<ul>
<li>log1</li>
<li>log2</li>
</ul>
</ul>
```
The markup of this PR is:
```html
<ul>
<li>explanation...</li>
<li>explanation...</li>
<li style="list-style-type:none;">
<ul>
<li>log1</li>
<li>log2</li>
</ul>
</li>
</ul>
```
In https://github.com/letsencrypt/website/pull/970 the "ct-logs" blacklist can be removed
=> Fix html for ct-logs shortcode

.travis.yml, netlify.toml
Update from Hugo 64.1 to Hugo 66. Differences:
- meta version
- lastmod in [ja] sitemap (one day)
- css minified (two lines switched without consequences)
Adds environment vars for travis: https://docs.travis-ci.com/user/environment-variables/
=> Hugo 66 and clean travis config

data/clients.json
openshift-acme client now supports ACME v2 protocol since https://github.com/tnozicka/openshift-acme/pull/92
=> Update openshift-acme client info to acme_v2

content/en/docs/a-warm-welcome-to-asn1-and-der.md
For IMPLICIT encoding, bit 8 of the tag should be set, to indicate the CONTEXT-SPECIFIC class,
and the tag number from the encoding instructions should be used.
Credit to @neilmaddog on Twitter for spotting the bug.
=> Fix a bug in EXPLICIT vs IMPLICIT section of ASN.1 doc

content/en/docs/a-warm-welcome-to-asn1-and-der.md
I noticed a few small typos and inaccuracies in the *[INTEGER encoding](https://letsencrypt.org/docs/a-warm-welcome-to-asn1-and-der/#integer-encoding)* section of *[A Warm Welcome to ASN.1 and DER](https://letsencrypt.org/docs/a-warm-welcome-to-asn1-and-der/)*, so I figured I'd help by fixing them. :slightly_smiling_face:
=> Fix small issues in INTEGER encoding section of ASN.1 doc

content/en/docs/a-warm-welcome-to-asn1-and-der.md
=> Fix typo in Octet String section of ASN.1 doc

netlify.toml
This fixes some CSP errors on the donate page created by a recent commit.
=> CSP broken after enabling shopify for summer giving campaign

i18n/en.toml, layouts/shortcodes/docs_index.html
These are two of the most important documents that we host,
so it makes sense to ensure that they are easily findable and
accessible from our website, rather that only found through the
Certificate Policies extension on our subscriber certs.
=> Add links to CP and CPS from docs index

content/en/docs/a-warm-welcome-to-asn1-and-der.md, src/css/_base.scss, src/js/main.js
Also, fix a few typos and replace all use of "spec" with
"specification."
=> Add decode links to DER examples.

content/en/post/2020-11-06-own-two-feet.md
This change relates to the ISRG root transition and the blog post at https://letsencrypt.org/2020/11/06/own-two-feet.html.
We have some Certbot-specific instructions published [on the community forum](https://community.letsencrypt.org/t/certbot-users-preparing-for-the-isrg-root-transition-january-11-2021/138059) as part of https://github.com/certbot/certbot/issues/8282.
Hopefully this will lead users, who do not visit the forums at all, to these instructions.
=> root transition: link to Certbot instructions

content/en/certificates.md
Added crt.sh links and removed text file links for all root and intermediate certificates to provide much cleaner, more powerful information. Noticed an inconsistency in two of the text files (PEM certificate appended at bottom of https://letsencrypt.org/certs/lets-encrypt-r3-cross-signed.txt and https://letsencrypt.org/certs/lets-encrypt-r4-cross-signed.txt).
=> Improve "Chain of Trust" (certificates.md) page

content/en/certificates.md
Moved "Let's Encrypt Authority X3" and "Let's Encrypt Authority X4" to the retired section and updated corresponding text to reflect these retirements and the transition to R3. Removed an unnecessary comma. Added overlooked crt.sh link to "ISRG Root OCSP X1".
=> Retired Certificates

content/en/certificates.md
Added crt.sh link for cross-signing root "DST Root CA X3" and clarified that cross-signing only applies to RSA intermediates.
Strangely, I was unable to find an entry in crt.sh for CN="TrustID X3 Root".
=> Enhanced "Chain of Trust" Page

content/en/docs/challenge-types.md
I've tested out TLS-ALPN-01 with wildcard certificates and it gave me the following error:
> ERROR: Validating this certificate is not possible using tls-alpn-01. Possible validation methods are: dns-01
As the documentation neither confirms nor denies that behavior, I've added the same line as with the HTTP-01 challenge.
=> Mention that TLS-ALPN-01 doesn't support wildcards

content/en/docs/client-options.md
The sentence:
> If you're already using one of the client below
...is missing an "s" on the word "client" and should read:
> If you're already using one of the clients below
=> Fix typo in client-options.md

content/fr/docs/revoking.md
Correction de deux fautes d'orthographe pour la page [https://letsencrypt.org/fr/docs/revoking/](https://letsencrypt.org/fr/docs/revoking/) en FR.
=> Update revoking.md FR

config/_default/languages.ja.toml
This PR translates the `description` param in `languages.ja.toml`. This string has not been translated and causes the Google search result to show the English description for the Japanese page.
Here is a screenshot of the Google search result for https://letsencrypt.org/ja/, showing English description:
=> Translate the website description into Japanese

.travis.yml, netlify.toml
Minor quotes differences, and align for table is using css instead of deprecated attributes.
=> Update Hugo to 0.79.1

data/clients.json
Adding a new Node.js client implementation, https://github.com/compulim/acme-http-01-azure-key-vault-middleware.
The package consists of 2 parts:
- Node.js enrollment agent to order certificate from Let's Encrypt and save it to Azure Key Vault
- Express middleware for handling HTTP-01 challenges, using pre-generated responses from enrollment agent
- ~If this PR is a translation, please read https://github.com/letsencrypt/website/blob/master/TRANSLATION.md first.~
=> Add new client implementation: acme-http-01-azure-key-vault-middleware

content/en/post/2021-01-21-next-gen-database-servers.md
This should make the Travis CI happier by not using a
nearly-deprecated stylistic (rather than semantic) element.
=> Use flexbox instead of <center> in blog

content/en/docs/cert-compat.md
I've reorganized a bit, to talk about trust stores rather than
browsers or other software. I've removed some unnecessary verbiage in
the intro paragraph, removed a note about XP and SNI, and reordered
the platforms list.
=> Update compatibility page to document X1 trust.

content/de/docs/glossary.md, content/en/docs/glossary.md, content/es/docs/glossary.md, content/fr/docs/glossary.md, content/he/docs/glossary.md, content/ko/docs/glossary.md, content/zh-cn/docs/glossary.md, content/zh-tw/docs/glossary.md, layouts/shortcodes/def.html, layouts/shortcodes/renderglossary.html
Partial Fix for #1194
The sort is done using `GetSortedMapValues` so it doesn't handle the locale. Sort in some language could be incorrect. Related: https://discourse.gohugo.io/t/alphabetical-sort-order/20246/4
An alternative could be to sort using javascript, but it may break the anchors.
See discussion https://community.letsencrypt.org/t/glossary-edit-perhaps-a-cosmetic-one/146360/20
=> Sort Glossary

data/clients.json
This adds an entry for the Terraform ACME provider, found at:
https://registry.terraform.io/providers/vancluever/acme/latest
This is a long-running ACME integration that I've been maintaining for
about 5 years, but for some reason never added it to the list!
=> data/clients.json: add Terraform ACME provider

content/en/docs/staging-environment.md
These are minor fixes atop a20c5cc28116112b515c0548ee7a0ab44736e089: a missing open-paren `(`, and a tense issue with regard to instructions about selecting RSA vs ECDSA chains.
=> Minor tweaks to Staging Hierarchy page

config/_default/languages.en.toml, config/_default/languages.he.toml, config/_default/languages.ru.toml
It's redundant (and serves no purpose).
=> Remove "Free SSL/TLS Certificates" from title

data/transparency.json
The Oak 2020 shard had expired and is no longer usable.
=> Update the Oak 2020 CT shard state

netlify.toml
Adds a redirection rule from https://lencr.org to https://letsencrypt.org/docs/lencr.org
=> Redirect lencr.org -> letsencrypt.org/docs/lencr.org

data/clients.json
Additional BASH-based client with native support for single-TXT-per-domain-name DNS providers such as Joker.com's DNS API; limited to only 384-bit ECDSA keys and DNS-01 challenge type.
=> Adding wdfcert.sh

data/clients.json
Adding HCL Domino V12 which now natively supports Let's Encrypt
=> Adding HCL Domino

content/en/getinvolved.md
The translation link now takes users to the Crowdin site to streamline translation activity.
=> Update 'Get Involved' translations link

content/en/docs/client-options.md
I don't know if this information is true other than from what I read on https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430/27 - but I guess that announcement is a reliable source.
I also edited https://en.wikipedia.org/w/index.php?title=Automated_Certificate_Management_Environment&type=revision&diff=1028228363&oldid=1027929407 based on the same source of information.
=> Refer to ACME v1 phase-out as already completed

content/en/docs/revoking.md
Since this doc starts with the assumption that revocation is
necessary due to key compromise (see the first paragraph),
we should suggest that subscribers pass the keycompromise
reason flag to cerbot when revoking their certificate.
=> Specify revocation reason flag in revoking doc

content/en/docs/expiration-emails.md
In response to [a note on the forum](https://community.letsencrypt.org/t/missing-expiration-note-email/160457/11?u=jcjones), this edit is to indicate the level of service we are intending to provide with the expiration mailer. In reality, with emails it's impossible to guarantee timely delivery on a mass scale, so subscribers should rely on automation first, and emails as a backup notice.
=> Make the expiration emails page indicate that it's a best-effort service

content/en/docs/cert-compat.md
Talk about the expiration in the past, and also update the "Platforms
that trust DST Root CA X3" section to indicate that those platforms will
no longer validate Let's Encrypt certificates.
=> Update cert-compat page for DST Root CA X3 expiry

content/en/certificates.md
This PR updates `content/en/certificates.md` and fixes the spelling of `compatibility`.
=> Change compatability to compatibility

content/es/how-it-works.md
Hello team
This PR changes the word `Emición`, it doesn't exist in the Spanish official dictionary (RAE). Instead, this PR aims to change it by Emisión, which is the correct word. 
Regards, 
Alberto R
=> Emición changed by Emisión

data/clients.json
Since ZeroSSL has changed ownership, making it more clear that Crypt::LE is a separate project now.
=> Making it more clear that Crypt::LE is a separate project.

content/en/docs/cert-compat.md
`cert-compat.md` says that ISRG Root X1 was added in Ubuntu 16.04, but, "with updates applied," it goes back farther.
For Ubuntu 12.04 LTS, it was added at some point during the ESM period. (ESM is paid support after normal support ends, but it's also free for up to 3 computers. Ubuntu likes TLAs!) Moreover, after ESM support ended this year, they actually published all the updated packages, so anyone can install them now.
Not sure if there's web-browser-readable evidence of that, but if you go to https://old-releases.ubuntu.com/ubuntu/dists/precise-updates/main/binary-amd64/, you can see that the files were updated a few months ago, and:
```
$ wget -q https://old-releases.ubuntu.com/ubuntu/dists/precise-updates/main/binary-amd64/Packages.bz2
$ rg -zA 2 "Package: ca-certificates" …
```
=> ISRG Root X1 is supported in Ubuntu 12.04 ESM

content/en/docs/cert-compat.md
In #1322, I got as far as figuring out that Ubuntu 10.04 LTS supported DST Root CA X3.
I'm a bad sleuth. It turns out 8.10, 9.04 and 9.10 did, too! (8.04 really didn't.)
I had checked the non-LTS release situation for *ISRG Root X1*, but I had only checked which LTS release added DST Root CA X3. :-(
cc @jsha
```
$ wget -q https://old-releases.ubuntu.com/ubuntu/dists/intrepid/main/binary-amd64/Packages.bz2
$ rg -zA 7 '^Package: ca-certificates$' Packages.bz2
5367:Package: ca-certificates
5368-Priority: important
5369-Section: misc
5370-Installed-Size: 724
5371-Maintainer: Ubuntu Core Developers <ubuntu-devel-discuss@lists.ubuntu.com>
5372-Original-Maintainer: Fumitoshi UKAI <ukai@debian.or.jp>
5373-Architecture: all
5374-Version: 20080514-0ubuntu1
$ wget -q …
```
=> Ubuntu 8.10 actually supported DST Root CA X3

i18n/it.toml
There's a minor typo in the Italian .toml file that needs to be fixed (it appears on the LE landing page)
=> Correct typo

content/en/docs/staging-environment.md
See the [Certbot documentation](https://certbot.eff.org/docs/using.html#certbot-command-line-options) for the explanation:
> --test-cert       Obtain a test certificate from a staging server
> --dry-run         Test "renew" or "certonly" **without saving any certificates to disk**
=> Fix wrong CLI param for staging certs

data/clients.json
This pull request updates the project URL for `acme-client-portable` from GitHub to sr.ht.
=> Update acme-client-portable URL

content/en/post/_index.md
Based on #686.
We don't have room for another top-level item, so I added this to the "About" menu.
@bdaehlie Let me know if you think this is sufficient or if I should look into an alternative.
=> Add blog to the main nav, as the last item of the about menu.

content/en/tlsalpnrevocation.md
Add a new page to the website, which provides instructions on
how to download and search the list of certificates affected by
the TLS-ALPN-01 TLS Version and OID Incident.
=> Add page for TLS-ALPN-01 Incident affected certs

content/en/tlsalpnrevocation.md
Include final date that affected certificate data for the TLS-ALPN-01 Incident will be available/hosted by Let's Encrypt.
=> Update TLS-ALPN-01 Incident Page

layouts/_default/_markup/render-link.html
This is a common source of infinite recursion (stack overflow) when the `linkify` option is enabled.
In the upcoming Hugo 0.94.0 building will fail without this patch:
```bash
Error: Error building site: "/Users/bep/dev/sites/website/layouts/_default/_markup/render-link.html:11:14": execute of template failed: template: _default/_markup/render-link.html:11:14: executing "_default/_markup/render-link.html" at <markdownify>:
error calling markdownify: text is already rendered, repeating it may cause infinite recursion
```
=> Avoid double-rendering of link .Text

data/transparency.json
- Update oak shard information
- Remove Testflume
- Add sapling testing log
This updates the data/transparency.json file with current log information.  However, there are still many prose references to the now-deleted "Testflume" log which need to be updated
=> Update Certificate Transparency Data

README.md, content/base-l10n/docs/duplicate-certificate-limit.md, content/de/docs/duplicate-certificate-limit.md, content/en/docs/duplicate-certificate-limit.md, content/es/docs/duplicate-certificate-limit.md, content/fr/docs/duplicate-certificate-limit.md, content/he/docs/duplicate-certificate-limit.md, content/id/docs/duplicate-certificate-limit.md, content/it/docs/duplicate-certificate-limit.md, content/ja/docs/duplicate-certificate-limit.md, content/ko/docs/duplicate-certificate-limit.md, content/pt-br/docs/duplicate-certificate-limit.md, content/ru/docs/duplicate-certificate-limit.md, content/sr/docs/duplicate-certificate-limit.md, content/sv/docs/duplicate-certificate-limit.md, content/uk/docs/duplicate-certificate-limit.md, content/vi/docs/duplicate-certificate-limit.md, content/zh-cn/docs/duplicate-certificate-limit.md, content/zh-tw/docs/duplicate-certificate-limit.md, layouts/shortcodes/docs_index.html, new-page.sh, src/css/_base.scss
- Add docs page for the Duplicate Certificate Rate Limit
- Add list entry to the Documentation page
- Fix CSS `bottom` spacing for single-nested unordered-list (`<ul>`) entries
- Add small script `new-page.sh` which automates the creation of new pages in
`content/en` and all stub no-translation documents for all other languages
=> Add docs for duplicate certificate rate limit

content/base-l10n/docs/failed-validation-limit.md, content/de/docs/failed-validation-limit.md, content/en/docs/failed-validation-limit.md, content/en/docs/rate-limits.md, content/es/docs/failed-validation-limit.md, content/fr/docs/failed-validation-limit.md, content/he/docs/failed-validation-limit.md, content/id/docs/failed-validation-limit.md, content/it/docs/failed-validation-limit.md, content/ja/docs/failed-validation-limit.md, content/ko/docs/failed-validation-limit.md, content/pt-br/docs/failed-validation-limit.md, content/ru/docs/failed-validation-limit.md, content/sr/docs/failed-validation-limit.md, content/sv/docs/failed-validation-limit.md, content/uk/docs/failed-validation-limit.md, content/vi/docs/failed-validation-limit.md, content/zh-cn/docs/failed-validation-limit.md, content/zh-tw/docs/failed-validation-limit.md, layouts/shortcodes/docs_index.html
- Add dedicated Failed Validation Limit docs page
- Add new Failed Validation Limit page to the `/docs/` index list
- Link to new Failed Validation Limit page to `/docs/rate-limits/`
=> Add new docs page for Failed Validation Limit

content/en/docs/revocation-reason-codes.md
Because we do not issue certificates with Subject Identity
Information, remove the `affiliationChanged` reason from the
set of acceptable revocation reasons.
Additionally, document that we may ignore the requested
reason under circumstances when we are confident that
a different reason is more appropriate. (This behavior is
controlled by Boulder's `MozRevocationReasons` feature
flag.)
=> Make revocation reasons doc stricter

content/base-l10n/docs/too-many-registrations-for-this-ip.md, content/da/docs/too-many-registrations-for-this-ip.md, content/de/docs/too-many-registrations-for-this-ip.md, content/en/docs/rate-limits.md, content/en/docs/too-many-registrations-for-this-ip.md, content/es/docs/too-many-registrations-for-this-ip.md, content/fi/docs/too-many-registrations-for-this-ip.md, content/fr/docs/too-many-registrations-for-this-ip.md, content/he/docs/too-many-registrations-for-this-ip.md, content/hu/docs/too-many-registrations-for-this-ip.md, content/id/docs/too-many-registrations-for-this-ip.md, content/it/docs/too-many-registrations-for-this-ip.md, content/ja/docs/too-many-registrations-for-this-ip.md, content/ko/docs/too-many-registrations-for-this-ip.md, content/pt-br/docs/too-many-registrations-for-this-ip.md, content/ru/docs/too-many-registrations-for-this-ip.md, content/sr/docs/too-many-registrations-for-this-ip.md, content/sv/docs/too-many-registrations-for-this-ip.md, content/uk/docs/too-many-registrations-for-this-ip.md, content/vi/docs/too-many-registrations-for-this-ip.md, content/zh-cn/docs/too-many-registrations-for-this-ip.md, content/zh-tw/docs/too-many-registrations-for-this-ip.md, layouts/shortcodes/docs_index.html
- Add dedicated Registrations Per IP limit docs page
- Link new Registrations Per IP limit page in the `/docs/` index list
- Link to new Registrations Per IP limit page to `/docs/rate-limits/`
=> Add docs for Registrations Per IP limit

content/en/docs/expiration-emails.md
We frequently see users on the Community just copy/pasting the expiry email. Usually I redirect them to this documentation page. It's almost always necessary to explain what happens using crt.sh.
I believe it would be a good thing if the documentation page I link to, also includes the part about ct log monitors as explained on the Community threads. That way one could not say the documentation is incomplete with regard to what happens in the Community threads.
This relatively simple addition refers to the use of ct log monitors to see a history of your certificates. This complements the part above it about adding/removing hostnames. Users might not remember doing that, so seeing the history on crt.sh is quite helpful I think and thus helpful to include it here.
- If this PR updates a file …
=> Add sentence about searching on ct log monitors

content/en/docs/expiration-emails.md
We send at 20 days and 10 days; we no longer send at 1 day.
=> Fix expiration mail dates

layouts/shortcodes/sponsors.html, src/css/_layout.scss, src/css/main.scss
Some logos on the sponsors page were taking up the full width, due to inconsistent sizes of the logos provided. Use flexbox to enforce more consistent layouts.
=> Sponsors page - improve consistency of logos, especially on mobile

content/en/docs/faq.md
We aren't returning 429s during overload anymore.
=> Change the URL to link to http 503

content/en/docs/lencr-org.md
This is no longer accurate, now that we are issuing CRLs for leaf certificates.
=> Remove note about CRLs being for intermediates

content/en/post/2022-05-19-nurturing-ct-log-growth.md
Fix incorrect path for 2022-05-19 blog post. Add an alias to redirect the old incorrect URL to the new one.
=> Fix path for 2022-05-19 blog post

content/en/docs/account-id.md
Recently, a new subcommand was added to Certbot: [`show_account`](https://github.com/certbot/certbot/commit/93c2852fdba34f14b294b38dcd27a0a8d94fe053)
While it was mainly intended to show stuff like email contact info of the account, the account ID is added to the output too. Therefore, for users running certbot 1.23.0 or newer could use this simple subcommand to fetch their account ID instead of the requirement to open JSON files.
While adding this info I also added a link to the Certbot homepage on the first mention of Certbot. Can't hurt methinks.
<s>**Note**: Certbot 1.23.0 hasn't been released yet. Therefore, I suggest waiting with merging this PR, if accepted, until the next release of Certbot.</s>
=> Mention Certbot `show_account` subcommand on Account ID page

content/de/certificates.md
this fixes a typo in the ISRG Root X1 section.
=> Fix typo for ISRG Root X1 crossignature

content/da/getinvolved.md, content/de/getinvolved.md, content/en/getinvolved.md, content/es/getinvolved.md, content/fi/getinvolved.md, content/fr/getinvolved.md, content/he/getinvolved.md, content/hu/getinvolved.md, content/id/getinvolved.md, content/it/getinvolved.md, content/ja/getinvolved.md, content/ko/getinvolved.md, content/ru/getinvolved.md, content/si/getinvolved.md, content/sr/getinvolved.md, content/sv/getinvolved.md, content/uk/getinvolved.md, content/vi/getinvolved.md, content/zh-cn/getinvolved.md, content/zh-tw/getinvolved.md
**PR Summary**:
The PR updates the location of the letsencrypt/boulder's `CONTRIBUTING.md` file which was moved from the root directory into `docs` directory. Also changed the branch from `master` to `main`.
- Previous location: https://github.com/letsencrypt/boulder/blob/master/CONTRIBUTING.md
- Current location: https://github.com/letsencrypt/boulder/blob/main/docs/CONTRIBUTING.md
Relevant docs page: https://letsencrypt.org/getinvolved
=> fix: update boulder's CONTRIBUTING.md location

content/en/docs/caa.md
Overhaul the CAA documentation page to remove references to outdated RFCs, streamline the guidance about where to put CAA records, introduce guidance about what to put in them, and describe the (relatively) new accounturi and validationmethods parameters.
Fixes https://github.com/letsencrypt/website/issues/1524
=> Update CAA documentation

data/clients.json
Add [njs-acme](https://github.com/nginx/njs-acme) project into ACME Client Implementations under `nginx` category
Fixed docker-compose file syntax issue along the way:
> validating /Users/ivanitskiy/src/github.com/letsencrypt/website/docker-compose.yml: (root) Additional property server is not allowed
=> Add njs-acme project into ACME Client Implementations under nginx category

docker-compose.yml
added missed services in docker-compose. Without this `docker compose` complains about file syntax. 
=> added missed services in docker-compose

config/_default/config.toml, config/_default/languages.da.toml, config/_default/languages.de.toml, config/_default/languages.en.toml, config/_default/languages.es.toml, config/_default/languages.fi.toml, config/_default/languages.fr.toml, config/_default/languages.he.toml, config/_default/languages.hu.toml, config/_default/languages.id.toml, config/_default/languages.it.toml, config/_default/languages.ja.toml, config/_default/languages.ko.toml, config/_default/languages.pt-br.toml, config/_default/languages.ru.toml, config/_default/languages.si.toml, config/_default/languages.sr.toml, config/_default/languages.sv.toml, config/_default/languages.uk.toml, config/_default/languages.vi.toml, config/_default/languages.zh-cn.toml, config/_default/languages.zh-tw.toml
When running this site with latest hugo version 0.117.0, there are a lot of warning thrown. This PR fixes all these warnings.
The site runs still fine with hugo v0.89.x, though.
=> Fix warn messages with latest hugo version 0.117.0

layouts/_default/single.html, layouts/partials/lastmod.html, layouts/partials/outdated_translation.html
Fix #1576 : 
It will always display the "outdated translation" warning, even for pages without `show_lastmod`
=> Separate the logic of outdated_translation vs lastmod

layouts/index.html
On the homepage for non-english languages, the blog posts were not listed. Even though Let's Encrypt can't translate blog posts into other languages, these blog posts should be displayed on all homepages. For non-english homepages, the links to blog posts will open in a new tab since those blog posts and their navigation systems are written in english.
=> Homepage - Show English blog post list for all languages

src/css/_donate.scss
On mobile, the color of monetary options goes invisible.
=> Donate Form fix

content/en/certificates.md
This was done for consistency.
=> Capitalize new Ex intermediate's CN

data/clients.json
Updated `lastmod` too. Not entirely sure if the typo correction warrants it, but it wasn't updated in the last change to this file anyways 58efd6dc90e8fd07cc5c99ff02711a8e0e809115.
=> Fix typo in wdfcert.sh comments in clients.json

content/en/upcoming-features.md
ECDSA intermediates are GA as of last week.  Update the "upcoming features" page as a result
=> Move ECDSA to complete section of upcoming features page

data/clients.json
Using the ahrefs.com/broken-link-checker/, I noticed this link was dead.
I don't see a replacement page on the website, so simply remove it.
=> Remove dead link to Hiawatha Webserver

data/clients.json, layouts/shortcodes/clients.html
Get rid of any clients that aren't ACMEv2 compatible, remove ACMEv2 labels from client list since we no longer need to differentiate.
=> ACMEv1 client cleanup

data/clients.json
Searched crates.io for ACME libraries using the "acme" search term and found the following seemingly reasonable options (both maintained and decently popular). Disclaimer: I maintain one of these.
Sorted here in order of decreasing popularity (by "recent downloads").
=> Add some Rust library options

content/en/docs/cert-compat.md
Debian Bullseye (11 / old-stable) ships ca-certificates version 20210119 as it can be checked in https://packages.debian.org/bullseye/ca-certificates. ISRG X2 root certificate was included on version 20230311 that's shipped with Debian Bookworm (12 / stable) as showed in https://packages.debian.org/bookworm/ca-certificates
=> Fix reported X2 debian compatibility

netlify.toml
Fixes #1702 
Because `certbot` includes a `.` right after the URL, it is easy for users to accidentally try to load a URL including the `.`.  This adds a redirect to make that less error-prone.
=> Allow trailing `.` in Terms of Service URL

content/en/donation-information.html
- The current hard wrapping was causing that this file had a wrong segmentation in Crowdin and we could not leverage our past translations at 100% because of mismatch with our translation memory.
=> Remove hard wrapping in donation-information.html

content/en/docs/cert-compat.md
ISRG Root X1 from 6.10 (with ca-certificates >= 2016.2.9)
ISRG Root X2 from 7.9 (with ca-certificates >= 2022.2.54)
=> Certificate compatibility for Red Hat Enterprise Linux (and derivatives)

data/transparency.json
This adds the new version of the sunlight logs.
I'm using the base64 version of the logID, which is standard elsewhere and is thus more useful generally.  I'll convert the other logs to the base64 version in a follow-on PR.
This information is also available on the logs pages themselves:
https://twig.ct.letsencrypt.org/
https://sycamore.ct.letsencrypt.org/
https://willow.ct.letsencrypt.org/
=> Replace Sunlight logs with the new "b" logs

data/transparency.json
Per a report I received via email from Censys, the key was missing a character.  Copy-paste problem.
=> Fix Willow 2025h2b's public key

config/_default/languages.ca.toml, config/_default/languages.cs.toml, config/_default/languages.da.toml, config/_default/languages.el.toml, config/_default/languages.he.toml, config/_default/languages.pl.toml, config/_default/languages.ru.toml, config/_default/languages.ta.toml, config/_default/languages.th.toml, config/_default/languages.tr.toml, config/_default/languages.uk.toml, config/_default/languages.vi.toml, config/_default/languages.zh-cn.toml, config/_default/languages.zh-tw.toml
- The `weight` parameter in the recently added languages was not correct causing incorrect order in the language menu selector.
=> Fixing the weight parameter to fix the order of the locales in the menu

data/transparency.json
The end date for 2025h2b was incorrect, so we are retiring that shard and introducing 2025h2c
=> New shard, Willow 2025h2c, replacing 2025h2b

config/_default/languages.en.toml
- I have added comments back to `config/_default/languages.en.toml` which is used as a source for translations and these comments are important so that people know how to create new such files. 
- Tested, the update does not cause a new warning. 
- If there is a problem, we may need to find a better way to keep these comments, either in this file or in the localisation instructions.
=> Add comments regarding weight, language and language codes to config/_default/languages.en.toml

data/clients.json
add docker openresty  image with auto ssl  to list， add docker nginx  image with auto ssl  to list
=> Add docker openresty image and nginx image(with auto ssl) to list

content/en/docs/rate-limits.md
Add documentation for the limits used to enforce automatic pausing of zombie clients: https://community.letsencrypt.org/t/automatic-pausing-of-zombie-clients/229642
=> Add ratelimits documentation for Automatic Pausing

content/en/docs/integration-guide.md
=> Remove suggestion for OCSP Stapling from the Integration Guide

content/en/docs/rate-limits.md
The two metaphors are mirrors of each other, and either works, but since we use the "token" bucket metaphor internally in Boulder, it's less confusing to use the same metaphor externally.
=> doc: switch from "leaky" to "token" bucket

content/en/docs/rate-limits.md, src/css/_base.scss
These numbers were taken from our production configuration and checked by @jcjones.
Fixes #1781
---
Link for reviewers:
https://deploy-preview-1794--letsencrypt.netlify.app/docs/rate-limits/#overall-requests-limit
=> docs/rate-limits: Document Overall Requests Limit and style tables

netlify.toml
Doing this to allow us to replace the deprecated resources.ToCSS function.
=> Bump version of Hugo used by Netlify to 0.130.0.

data/transparency.json
2026 shards are usable.  2024h1 is rejected.
=> Update Oak log shard status

content/en/docs/cert-compat.md
Updated compatibility for Java
Java releases: https://www.java.com/releases/
=> Update ISRG Root X2 Certificate compatibility for Java

content/en/post/2025-02-20-first-short-lived-cert-issued.md
We used censys at first because crt.sh was taking a long time to catch up.
=> Replace censys link with crt.sh in short lived cert blog post

content/en/docs/expiration-emails.md
The link should point to the blog post, instead of the documentation itself.
=> Fix expiration email EOL blog post link

themes/le-2025/layouts/_default/rss.xml
Re: #1866 & #1867 restores previous RSS template to not include any site pages.
=> Restore previous RSS template

content/base-l10n/sponsors.html
- No longer needed due to https://github.com/letsencrypt/website/commit/cbbce229ac2cc321a9b1b0221822b9feca77a6e9
=> Removing content/base-l10n/sponsors.html

content/en/docs/rate-limits.md, content/en/docs/staging-environment.md
=> rate limits: update for staging, and errant value in production

content/da/docs/rate-limits.md, content/zh-cn/docs/rate-limits.md
- Changes due to https://github.com/letsencrypt/website/pull/1881/
=> Fixing rate-limits.md in DE and ZH-CN

content/en/docs/faq.md
Add some nuance to account for per-profile authz lifetimes
Fixes https://github.com/letsencrypt/website/issues/1895
=> Update FAQ entry about validation reuse

content/en/certificates.md
Because we frequently get people being confused that the "Validity" fields of our roots don't match the "notAfter" dates in their certificates, rephrase those bullet points to try to reduce misunderstandings.
=> Rephrase chains of trust validity bullet points

content/en/docs/profiles.md
AIA OCSP URIs were removed from certificates issued under the classic profile on May 7.
Fixes https://github.com/letsencrypt/website/issues/1908
=> Document removal of OCSP from Classic profile

content/en/docs/staging-environment.md
Update the docs to note more logs are used, including some ct-test-srv instances.
=> Update staging SCTs documentation

content/en/docs/profiles.md
Once the blog post is announced, this can reference it for deprecation timelines.
Adds and hyperlinks footnotes, and reformats tables.
This needs to merge after https://github.com/letsencrypt/website/pull/1911
=> Add notes about ClientAuth EKU to profiles

content/en/docs/integration-guide.md
Add recommendation to check ARI >= 2x/day for when to renew.
Re-word 66% of lifetime to indicate it's a backstop to ARI; add 50% of lifetime for <10d certs.
Remove notes about subscriber email addresses, since we no longer collect them.
Trivial copy and formatting edits throughout.
=> Add recommendation to check ARI >= 2x/day for when to renew

content/en/docs/challenge-types.md
Such a list can become out of date, as it already is.
Resolves issue #1491.
=> Don't list specific client support in challenge types doc.

content/en/post/2023-07-10-cross-sign-expiration.md
=> Remove cross sign expiration post from the About menu

content/en/post/_index.md
When previewing the site with latest hugo version `0.148.2`, a warning is printed out:
```
WARN  "/home/xxx/lets-encrypt-website/content/en/post/_index.md:1:1": duplicate menu entry with identifier "Blog" in menu "main"
```
This PR fixes that issue.
=> Fix warning 'duplicate menu entry'

.github/workflows/test.yaml
This PR bumps GitHub actions to their latest versions. It also corrects incorrect attribute `node_version` on the way.
=> Bump GitHub actions to latest versions

content/en/post/_index.md
Reverts letsencrypt/website#1983
This broke the "Blog" link in top navigation.
=> Revert "Fix warning 'duplicate menu entry'"

content/en/how-it-works.md
* Change remaining usage of "agent" to "client"
* Clarify renewal process (don't imply that subscribers don't have to validate again to renew)
* Add note about usage of plain HTTP in validation process
Resolves #1398.
=> Updates to How It Works page

content/en/post/2025-08-14-rfc-6962-logs-eol.md
November 30 is shortly after we expect our new Sunlight logs to be Usable.
February 28 is 90 days later.
=> Update dates for Oak EOL

client-data-lastmod.py, client-data-prune.py, content/en/docs/client-options.md, data/clients.json
This PR includes commits to manually incorporate data from all pending client PRs (those tagged as client-options, at https://github.com/letsencrypt/website/pulls?q=is%3Apr+is%3Aopen+label%3Aclient-options).
It also includes a new Python script to add the last commit date to each client based its detected git repository URL, if any. That script has been run once, and the results are also included in the PR.
This data can be used to split out clients that are no longer being maintained into a separate JSON file, or to hide them on the Let's Encrypt site.
I added an additional script that uses the data to entirely remove such clients from the JSON file.
=> Add client data updates, last modification date script, and data about clients' last modification dates

netlify.toml
The -test redirects worked well, so move the real redirects here.
=> Host cp.letsencrypt.org and cps.letsencrypt.org

data/clients.json
Haproxy 3.2 and later supports generating certificates with ACME protocol.
=> Add haproxy to clients.json
