letsencrypt/website

docs/acme-protocol-updates.md
docs/cert-compat.md
docs/faq.md
docs/index.md
docs/integration-guide.md

Clarify one vs. many account recommendation for hosting providers. Remove broken link in FAQ. Introduce cert compat and acme update docs.

Various documentation updates

---

docs/faq.md

This commit adds a FAQ entry for which signature algorithms we support in CSRs.

Add a FAQ entry for CSR sigalg support.

---

docs/client-options.md

See https://www.plesk.com/extensions/letsencrypt/

Add info about Plesk+LE integration.

---

stats.md

These aren't really useful to non-Boulder developers.

Remove OCSP data from public stats page.

---

docs/acme-protocol-updates.md
docs/cert-compat.md
docs/client-options.md
docs/expiration-emails.md
docs/faq.md
docs/integration-guide.md
docs/rate-limits.md
docs/staging-environment.md

Add last updated date to all documentation pages.

---

docs/client-options.md

The previous link was deprecated.

Fix link of AcmePHP client

---

jobs.md

Adding the Systems Administrator position back to the jobs page.

Jobs sysadmin

---

jobs.md

Unbalanced parens make programmers CrAzY! :-)

Balance parens

---

_includes/header.html
about.md
certificates.md
docs/account-id.md
docs/client-options.md
docs/index.md
isrg.md

Intent is to resolve issue #31

Improve nav structure, add stats to nav

---

js/stats.js
stats.md

This kicks off the TSV fetch without waiting for the whole document to finish
loading. It also puts the "var" keyword on some variables.
@jcjones this is a PR to pull changes into your PR. :-)

Load TSV asynchronously.

---

docs/acme-protocol-updates.md

Also switch  GitHub links to point to the correct branches for prod/staging.

Update ACME draft number references

---

docs/client-options.md

ACME client implementation in python for nginx under 350 lines of code.

added python client for nginx

---

stats.md

Wording updates for the stats page from S.

Update text per S.

---

_config.yml
_includes/footer.html
_sass/_base.scss
_sass/_layout.scss
donate.html
index.html

I updated some stuff on the homepage and the donate page and in the footer to drive traffic to the crowdfunding campaign. The campaign is not live yet, but I think this is the URL where it will be: https://www.generosity.com/community-fundraising/make-a-more-secure-web-with-let-s-encrypt.  If it changes after the campaign launches, just update the `crowdfunding_url`in the `config.yml` and it will update all the "Donate" buttons and links.

Crowdfunding updates

---

docs/client-options.md

Just adding a further client option to the list.

add github.com/costela/wile to client-options

---

docs/cert-compat.md

updated page date to account for PR#101

---

docs/client-options.md

The current implementation is broken, the new fork fixes it.
Reference: https://github.com/kuba/simp_le/issues/118#issuecomment-266232657

Update link to simp_le

---

docs/rate-limits.md
docs/staging-environment.md

Also, remove "recent" comment from Overall Requests and tighten up the language
a little to match the other stanzas.

Add Failed Validations to rate limits page.

---

docs/client-options.md

added key Manager Plus client under java

key Manager Plus client added under java

---

docs/client-options.md

- Written in Clojure
- Runs on the command line.
- Self contained binary

Added Certificaat to the list of client options

---

_includes/header.html
_sass/_layout.scss
js/main.js

* Keyboard/tab accessibility
* Skip link for screen readers

Navigation menu accessibility improvements

---

certs-redirect.html

Add a redirect from /certs/ to /certificates/

---

documents/ISRG-CP-v2.0.html
documents/ISRG-CPS-v2.0.html

This was generating spurious internal scroll bars on our CPS and CP.

Replace overflow: scroll with auto.

---

docs/rate-limits.md

This will allow us to link directly to specific rate limits.
Also update the Failed Validations limit to no longer say "recently", and link
to the staging environment.

Add named anchors to rate limit doc.

---

upcoming-features.md

As per https://letsencrypt.org/2017/06/14/acme-v2-api.html

Added ACME v2 to upcoming features

---

docs/rate-limits.md

This reverts commit 159a7388397b790961be8c4572007f5f4a9a5755.
Page modification date is set as today.

Revert #177 - Renewal order matters once more.

---

docs/expiration-emails.md

Add info about unsubscribe only being valid for 1 year

---

jobs.md

Putting up the listing for the new sysadmin position we are opening.

Post listing for sysadmin opening

---

stats.md

This way you can link to a specific graph.

Add anchors for sub-sections of stats.

---

docs/caa.md

Resolves https://github.com/letsencrypt/website/issues/208

Update the CAA docs page with Ballot 214 results.

---

docs/client-options.md

This time without strange deletions :)

Added AutoACME, clarified Windows web server

---

layouts/_default/rss.xml

Escape RSS text fields

---

content/docs/client-options.md

Add EasyHTTPs client support!

---

content/docs/client-options.md

Added a link to the LEClient PHP library repository on GitHub.

Added link to LEClient PHP library

---

content/docs/_index.md
content/docs/certificates-for-localhost.md

Also add keyUsage and extendedKeyUsage to OpenSSL example.

Link to localhost docs from index.

---

content/docs/certificates-for-localhost.md

I used the wrong linkification style for these.

Fix linkification errors.

---

i18n/en.toml
layouts/index.html
layouts/post/list.html

Better to fix it now before you start translating.

Put the entire a href for RSS feed  inside the i18n file

---

content/docs/integration-guide.md

The information on both was out of date.

Remove Must Staple / SCT from integation guide.

---

content/post/_index.md

The TODO has been resolved a long time ago. The page content isn't rendered for this file, so this is just to remove some confusion for people seeing a TODO in a file.

Remove TODO

---

content/docs/staging-environment.md

See https://github.com/certbot/certbot/issues/5365

Certbot supports ACMEv2

---

content/docs/client-options.md

added lambda due to acme v2 support addition

---

content/docs/client-options.md

add SSL For Free to ACME v2 Compatible client(wildcard)

update SSL For Free to ACME v2 Compatible client

---

content/docs/client-options.md

also fixed the modification date to today

added github org

---

content/docs/client-options.md

Added publishlab/node-acme-client to libraries and list of ACMEv2 compatible clients.

Added publishlab/node-acme-client

---

content/post/2018-04-04-sct-encoding.markdown

Hey @jsha, just noticed this very minor mistake while reading your awesome blog post. Feel free to close this PR if you want to write it differently :)

Fix a hex->dec conversion in the SCT encoding post

---

content/en/docs/acme-protocol-updates.md

Minimal changes to add the ACME v2 entry points

Missing ACME v2

---

content/en/docs/client-options.md

Ruby acme-client now support v2

Ruby acme-client now support v2

---

layouts/_default/rss.xml

Fix for #296
Tested on local copy of the site with few Feed readers

Fix RSS feed

---

content/en/docs/client-options.md

Added Certes to clients, libraries, and list of ACMEv2 compatible clients.

Add Certes to client options list.

---

content/en/upcoming-features.md

https://community.letsencrypt.org/t/tls-alpn-validation-method/63814/3
The wording of the details have been updated too:
"We're working on specifying and implementing a replacement" => "We've specified and implemented a replacement"
"Introducing a replacement is important" => "Introducing a replacement was important"

TLS ALPN Challenge Support: Enabled July 12, 2018

---

content/en/docs/client-options.md

Would you please consider adding this web firewall server with integrated ACME to the list, thank you!

Add ruxy WAF proxy server with ACME support

---

content/en/docs/faq.md

To have a better place to redirect people that just "please see previous discussions"
Ex.: https://community.letsencrypt.org/t/scammers-using-lets-encrypt-ssl-cert/66785/5

Phishing entry

---

content/en/docs/client-options.md

PowerShell implementation of ACME v2 - added as client option.
Source available via https://github.com/PKISharp/ACMESharpCore-PowerShell

Added ACME-PS client

---

README.md
TRANSLATION.md
content/en/docs/client-options.md

A summary of all discussions that happened during the French translation, that could be useful.
I'm not sure README.md is the perfect place, but at least it's a visible one to encourage translators for come forward!

I18n guidelines

---

layouts/partials/footer.html

I changed the postal address in the footer to meet https://schema.org/PostalAddress

Make footer address meet PostalAddress schema

---

i18n/es.toml

Spanish "Sponsor" string for home page

---

content/fr/stats.md

Fr Fix for #418

---

content/es/stats.md

Sync changes to the Spanish site from the English site regarding stats

---

content/en/docs/client-options.md

LiveConfig integrates with Let's Encrypt since 11/2015.

added "LiveConfig" to list of projects integrating with Let's Encrypt

---

content/es/upcoming-features.md

Sync with upstream changes

---

content/en/getinvolved.md

To help people discovers they can improve it or its translations
(rather than discover it by chance while browsing the first given link https://github.com/letsencrypt/)

Emphasis on the fact that they can help improve the website and its translations

---

content/fr/upcoming-features.md

update upcoming features

---

content/fr/getinvolved.md

i18n Fr: Emphasis on the fact that they can help improve the website and its translations

---

content/es/docs/staging-environment.md

don't use --staging (#456)

---

config.toml
layouts/shortcodes/def.html

0.55 is a rather big release, and I have used this repo as one of the many test sites.
With these 2 commits, there are no diffs between the site built with 0.54 and 0.55.
0.55 should not be too long away, but you can merge this now if you want. The first commit is an obvious bug fix.

This PR contains 2 fixes/updates to prepare for Hugo 0.55.

---

content/de/certificates.md

refers to https://github.com/letsencrypt/website/pull/446

add identrust download link in German translation

---

content/fr/certificates.md

Add identrust download link in French translation

---

data/clients.json

First version of lets-proxy is good work, but hard to test and support.
Lets-proxy2 - same idea, but rewrite from scratch.

Add lets proxy2

---

.travis.yml

Update travis for Hugo 55.6

---

content/en/docs/rate-limits.md
content/ru/docs/rate-limits.md

Greetings!
Fix issue #539 , adjust *lastmod* value in sections **en**/docs/rate-limits.md and **ru**/docs/rate-limits.md

Fix issue #539

---

data/clients.json

This client is written in D. See ReadMe for more details.

Add ACME client written in the D computer language

---

config.toml

URL was not set; Link was empty

Added URL for languages.de.menu.main

---

i18n/es.toml
layouts/_default/single.html

es for #546

---

content/de/donate.html
content/en/donate.html
content/es/donate.html
content/fr/donate.html
content/pt-br/donate.html
content/ru/donate.html
content/zh-cn/donate.html

Followup from #588, thanks @tdelmas!

Update lastmod field for fundraiser changes.

---

layouts/shortcodes/fundraiser.html

Changed text based on request from fundraising team

Small text updated to fundraiser shortcode

---

data/clients.json

Please add the Apache HTTP Server implementation and its separately available mod_md releases to your list. Thank you.

Adds Apache httpd/mod_md information.

---

i18n/zh-cn.toml

Adds [english_is_canonical]

---

layouts/robots.txt

Cf. https://github.com/gohugoio/hugo/issues/4678

Add Sitemap link in robots.txt

---

content/ja/about.md
content/ja/contact.md
content/ja/stats-dashboard.md
content/ja/upcoming-features.md

Add new translations for following pages:
- `about.md`
- `contact.md`
- `upcoming-features.md`
- `stats-dashboard.md`

[ja] Add Japanese translations

---

data/clients.json

Adding two ACME clients for Microsoft Azure.

Adding AppService and KeyVault Acmebot

---

data/clients.json

I've added the popular Acme PHP client and its core library to the `clients.json` file.
https://github.com/acmephp/acmephp
Docs: https://acmephp.github.io/documentation

Added Acme PHP client & library

---

content/de/stats.md
content/en/i18n.md
content/es/stats.md
content/fr/stats.md
content/ja/stats.md
content/ko/stats.md
content/ru/stats.md
content/zh-cn/stats.md
content/zh-tw/stats.md
layouts/shortcodes/i18n_status.html

- Add missing lastmod and update when necessary 
- Force build to fail if lastmod is missing

I18n stats and lastmod

---

layouts/shortcodes/i18n_status.html

At the bottom of https://letsencrypt.org/i18n

Add some i18n metrics

---

content/en/_headers
static/js/stats.js

We will be moving the site hosting to Netlify from self hosted. These changes help enable that migration.
- Add _headers to enable Content Security Policy and other security headers
- Pull stats files from external source.
At the same time as this PR I have turned on Netlify to build the site from the master branch and  build preview deploys on each pull request. We will start seeing comments from the Netlify build bot and be able to preview changes. The Netlify site will not go live until I change DNS which I am not going to do just yet but probably within the next 1-2 weeks if everything looks good.

Netlify migration prep

---

i18n/en.toml
layouts/_default/single.html
layouts/partials/langs.html
layouts/shortcodes/lastmod.html

Cf. https://support.google.com/gsa/answer/6329153?hl=en

code organization and googleoff/googleon

---

content/zh-cn/docs/staging-environment.md
content/zh-cn/how-it-works.md
content/zh-cn/stats.md

Cf https://github.com/letsencrypt/website/pull/616#issuecomment-536237391

Fix zh-cn merge

---

content/es/docs/_index.md
content/ru/docs/_index.md

The extra new lines in the the source create extra `<p>` with 15px bottom margin tag in the output.
This PR removes these extra lines in all `content/*/docs/_index.md` files.

Remove unnecessary new lines

---

data/clients.json

Also removed what seem to be stray newline there.

Add acme-cert-tool client implementation

---

content/en/documents/ISRG-CP-v2.3.html

@bdaehlie If you could validate this PR as it touches the CP?

Link in CP-v2.3: move parenthesis outside the link

---

content/en/documents/ISRG-CPS-v2.6.html

Typo in CPS link to repository

---

i18n/en.toml
i18n/fr.toml
layouts/shortcodes/docs_index.md

Differences ACME Draft =>Differences ACME RFC

---

static/js/stats.js

Better function separation
Doesn't download files that are not needed

Clean stats.js

---

data/clients.json

Key Manager Plus is ACME v2 Compatible

Key Manager Plus ACME v2 campatible

---

content/en/docs/client-options.md

* Added extra blurb about the ACMEv1 end of life
* Converted curly apostrophe characters to standard single quotes

Update ACMEv1 End of Life message

---

content/en/docs/ct-logs.html
content/es/docs/ct-logs.html
content/ja/docs/ct-logs.html
content/ko/docs/ct-logs.html
content/ru/docs/ct-logs.html
content/zh-cn/docs/ct-logs.html

Fix #767
https://html.spec.whatwg.org/multipage/images.html#alt

Add missing alt on link/picture

---

content/base-l10n/docs/godaddy.md
content/de/docs/godaddy.md
content/en/docs/godaddy.md
content/es/docs/godaddy.md
content/fr/docs/godaddy.md
content/id/docs/godaddy.md
content/ja/docs/godaddy.md
content/ko/docs/godaddy.md
content/pt-br/docs/godaddy.md
content/ru/docs/godaddy.md
content/sr-sp/docs/godaddy.md
content/zh-cn/docs/godaddy.md
content/zh-tw/docs/godaddy.md
layouts/shortcodes/docs_index.md

Note: The addition to docs_index.md causes Hugo to fail the build with:
```
ERROR 2019/12/02 19:49:52 Unknown page "/docs/godaddy"
```
But I can't figure out why. I'd love some extra eyeballs to help figure out
what I'm doing wrong.

Add documentation on use with GoDaddy.

---

layouts/shortcodes/docs_index.md

cf https://github.com/letsencrypt/website/pull/784#issuecomment-561091451

Better error message when missing template placeholders

---

content/ru/docs/faq.md

Forget to adjust year in "lastmod" field in PR #788 
File itself is up to date

ru/docs/faq.md is up to date, but "lastmod" is not

---

i18n/en.toml
i18n/sv.toml
layouts/index.html

Add support for translating the annual report announcement in the main banner and translate it to Swedish.

Translation of annual report announcement

---

config/_default/languages.toml

improve zh-tw translate in languages.toml

---

content/sv/how-it-works.md

Fix one spelling mistake in the Swedish translation of How It Works and
improve the wording of one sentence to clarify.

Swedish spelling and wording, How It Works

---

content/de/donate.html
content/en/donate.html
content/es/donate.html
content/fr/donate.html
content/id/donate.html
content/ja/donate.html
content/ko/donate.html
content/pt-br/donate.html
content/ru/donate.html
content/sr-sp/donate.html
content/sv/donate.html
content/zh-cn/donate.html
content/zh-tw/donate.html
layouts/shortcodes/donorbox.html

Donorbox shortcode and better lang selection

---

data/clients.json

add esp32-acme-client

---

i18n/sv.toml

As suggested by @tdelmas in pull request #809.

Swedish translation of PayPal title

---

content/es/privacy.md
content/ko/privacy.md
content/zh-cn/privacy.md

Update privacy.md translations

---

content/fr/about.md

Link to annual report in /about/ in French

---

content/fr/how-it-works.md

linkTitle for how-it-works in French

---

content/de/contact.md
content/fr/contact.md
content/id/contact.md
content/ja/contact.md
content/ko/contact.md

And update `lastmod` when possible (not possible when https://github.com/letsencrypt/website/commit/a52153620167d7b92fb4b6d2c19aa55fb5261353 not yet applied)

Apply #633 to translations

---

content/de/donate.html
content/es/donate.html
content/fr/donate.html
content/id/donate.html
content/ja/donate.html
content/pt-br/donate.html
content/sr/donate.html
content/zh-tw/donate.html

I've checked, now thanks to shortcodes they are all up-to-date.

Fix lastmod for translations of /donate/

---

i18n/ru.toml
package-lock.json

adjust statements in ru.toml

---

content/ja/docs/client-options.md
content/ja/docs/staging-environment.md

Hello, I translated another documentation page:
- https://letsencrypt.org/ja/docs/staging-environment/

[ja] Translate acme-protocol-updates.md and client-options.md into Japanese

---

content/en/docs/client-options.md

- I fixed a few words in the page.
- I also remove the word "Your" from the last section.
I removed "your" because clients can be added by someone who is not author.

Fix words in client-options.md

---

content/ja/about.md
content/ja/become-a-sponsor.html
content/ja/contact.md
content/ja/docs/ct-logs.html
content/ja/docs/faq.md
i18n/ja.toml

This PR updates out of data translations to the latest ones. I've checked the pages needed to be updated in: Translation status - https://letsencrypt.org/i18n/.

[ja] Update Japanese Translation

---

content/en/docs/staging-environment.md

A community member pointed out that this is a good place to mention Pebble. Often ACME client developers will be using the staging environment to vet their code and Pebble may be a better fit.

docs: add Pebble section to staging-environment.md

---

content/en/contact.md

Improve contact page description

---

content/en/jobs/_index.md
netlify.toml

Use Netlify redirects instead of inline js

Clean redirects

---

CODE_OF_CONDUCT.md
contributing.md

See: 
- #590 
- https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors#adding-a-contributing-file
- https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project

Create contributing.md and CODE_OF_CONDUCT.md

---

content/de/docs/ipv6.md
content/en/docs/ipv6.md
content/es/docs/ipv6.md
content/fr/docs/ipv6.md
content/id/docs/ipv6.md
content/ja/docs/ipv6.md
content/ko/docs/ipv6.md
content/pt-br/docs/ipv6.md
content/ru/docs/ipv6.md
content/sr/docs/ipv6.md
content/sv/docs/ipv6.md
content/zh-cn/docs/ipv6.md
content/zh-tw/docs/ipv6.md
layouts/shortcodes/docs_index.md

content/docs: add page describing IPv6 gotchas.

---

content/zh-cn/certificates.md
content/zh-cn/docs/cert-compat.md
content/zh-cn/docs/ct-logs.html
content/zh-cn/docs/ipv6.md
content/zh-cn/docs/rate-limits.md

[zh-cn] Update Translations

---

config/_default/languages.toml

Following a comment of Tom
(https://github.com/letsencrypt/website/pull/898#issuecomment-583726683)

[vi] Update languageName to "Tiếng Việt"

---

content/vi/about.md

Translate about.md to Vietnamese.

[vi] Translate about.md

---

DOCUMENTATION.md
config/_default/languages.toml

Cf https://github.com/letsencrypt/website/pull/911#issuecomment-583562918

Update technical documentation

---

content/en/post/2015-12-3-entering-public-beta.markdown

To update an old broken link that still can be useful:

Fix old certbot link

---

content/de/docs/ct-logs.html
content/en/docs/ct-logs.html
content/en/post/2016-4-12-leaving-beta-new-sponsors.markdown
content/en/post/2016-6-22-https-progress-june-2016.markdown
content/en/post/2016-8-5-le-root-to-be-trusted-by-mozilla.markdown
content/en/post/2017-1-6-le-2016-in-review.markdown
content/en/post/2017-6-28-hundred-million-certs.markdown
content/es/docs/ct-logs.html
content/ja/docs/ct-logs.html
content/ko/docs/ct-logs.html
content/ru/docs/ct-logs.html
content/zh-cn/docs/ct-logs.html
content/zh-tw/docs/ct-logs.html

The class "text-center" is defined as "text-align: center;"
https://developer.mozilla.org/fr/docs/Web/HTML/Element/center

Replace obsolete <center> element with <p class="text-center">

---

content/de/sponsors.html
content/en/documents/ISRG-CP-v2.0.html
content/en/documents/ISRG-CP-v2.1.html
content/en/documents/ISRG-CP-v2.2.html
content/en/documents/ISRG-CP-v2.3.html
content/en/documents/ISRG-CP-v2.4.html
content/en/documents/ISRG-CPS-v2.0.html
content/en/documents/ISRG-CPS-v2.1.html
content/en/documents/ISRG-CPS-v2.2.html
content/en/documents/ISRG-CPS-v2.3.html
content/en/documents/ISRG-CPS-v2.4.html
content/en/documents/ISRG-CPS-v2.5.html
content/en/documents/ISRG-CPS-v2.6.html
content/en/documents/ISRG-CPS-v2.7.html
content/en/sponsors.html
content/es/sponsors.html
content/fr/sponsors.html
content/id/sponsors.html
content/ja/sponsors.html
content/ko/sponsors.html
content/pt-br/sponsors.html
content/ru/sponsors.html
content/sr/sponsors.html
content/sv/sponsors.html
content/zh-cn/sponsors.html
content/zh-tw/sponsors.html
layouts/shortcodes/sponsors.html

https://www.w3.org/TR/html4/present/graphics.html#h-15.1.2
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div#Attributes

Replace deprecated html attribute align="center" with class "text-center"

---

DOCUMENTATION.md
content/en/i18n.md
layouts/partials/head.html

And it will be used by  #885 to not index the "book" and by #888 to filter results as well.

Adds the do_not_index option to pages

---

data/clients.json

simple decoupled le client added that suits multi tenant solutions

added afosto's client to the list of client integrations

---

static/.well-known/security.txt

https://securitytxt.org/
https://tools.ietf.org/html/draft-foudil-securitytxt-08
https://scotthelme.co.uk/say-hello-to-security-txt/

Adds /.well-known/security.txt

---

content/en/post/2016-9-20-what-it-costs-to-run-lets-encrypt.markdown

Cf https://github.com/letsencrypt/website/commit/d07d701efeeea6bbe685f341e9a2cc00feb45b5d

Fix spacing

---

layouts/partials/header.html
src/css/_nav.scss
src/js/main.js

New behavior is based on clicks not hovering.

new menu behavior, click not hover

---

content/ja/docs/faq.md

Hello, this PR is just a typo fix for the translation `content/ja/docs/faq.md`.

[ja] Fix a typo in faq.md.

---

content/zh-cn/upcoming-features.md

I forget to update the page date & content for upcoming-features.md ....
Edited the contents but forget to add enabled date..

[zh-cn] Fix upcoming-features.md

---

layouts/partials/footer.html

Fix invalid html

---

content/en/_headers

Was for #713 but deprecated by #948
Fix #957
And add more comments

Remove cdnjs.cloudflare.com from CSP

---

content/en/docs/rate-limits.md

Note both v1 and v2 endpoints with overall rl

---

content/en/docs/ct-logs.html
data/transparency.json
i18n/en.toml
layouts/shortcodes/ct_logs.html

Boulder calls this window_start and window_end.
Google calls this the start_inclusive and end_inclusive times per https://www.gstatic.com/ct/log_list/v2/all_logs_list.json.

Document the time range that a CT shard is available for use

---

content/en/caaproblem.md

Added a curl call to check the caaproblem website

---

content/en/caaproblem.md

Added Hanno's parallelizable checkhost script

---

content/zh-cn/docs/challenge-types.md
content/zh-cn/docs/client-options.md
content/zh-cn/docs/ct-logs.html
content/zh-cn/docs/rate-limits.md
content/zh-cn/docs/revoking.md

This PR updates 5 files in the zh-cn directory.

[zh-cn] update translation

---

content/de/docs/faq.md
content/en/docs/faq.md
content/es/docs/faq.md
content/ja/docs/faq.md
content/pt-br/docs/faq.md
content/ru/docs/faq.md
content/sv/docs/faq.md
content/zh-cn/docs/faq.md
content/zh-tw/docs/faq.md

To avoid useless redirect.
Cf https://github.com/letsencrypt/website/pull/964#pullrequestreview-368398881 and #807

Update safebrowsing url

---

content/en/docs/ct-logs.html

netlify.toml already contains that redirect. If complicate the translation to have it here.

Remove useless alias

---

.travis.yml
netlify.toml

Reverts letsencrypt/website#1005

Revert "Update from Hugo 66 to Hugo 67.1"

---

config/_default/languages.fr.toml
i18n/fr.toml

Update french translation :
https://github.com/letsencrypt/website/issues/937
Separate the pull request from :
https://github.com/letsencrypt/website/pull/1024

Transfr: Update french translation

---

content/en/docs/ct-logs.html

Typo fixed

---

src/css/_base.scss

Replace overflow-x:scroll with auto.

---

content/en/docs/a-warm-welcome-to-asn1-and-der.md

Correct comment about DER encoding of timezones.

---

data/clients.json

* Included automatoes at the end of python clients.
* updated lastmod date

Added automatoes to the list of client options.

---

content/base-l10n/docs/_index.md
content/de/docs/_index.md
content/en/docs/_index.md
content/es/docs/_index.md
content/fr/docs/_index.md
content/id/docs/_index.md
content/ja/docs/_index.md
content/ko/docs/_index.md
content/pt-br/docs/_index.md
content/ru/docs/_index.md
content/sr/docs/_index.md
content/sv/docs/_index.md
content/vi/docs/_index.md
content/zh-cn/docs/_index.md
content/zh-tw/docs/_index.md

Remove useless entry

---

.htmlhintrc

Remove attr-unsafe-chars from htmlhint

---

content/en/docs/a-warm-welcome-to-asn1-and-der.md

Cf https://github.com/letsencrypt/website/commit/461326c9f699f1cf9ed15b53625865b131240028

Update lastmod for "Removing hiring note from "A Warm Welcome""

---

content/en/docs/a-warm-welcome-to-asn1-and-der.md

Remove job link from "A Warm Welcome"

---

content/en/certificates.md

it was not updated with fd9645747b6d19

correct last updated date

---

content/en/certificates.md

was not update with cdfa969f9c09c3584741c655b20ccde9524ddc4a
once again ;-)
#1105

Update last modified date

---

data/clients.json

Also update Caddy's entry.
Let me know if I got anything wrong 😅  Thanks!

Add ACMEz to clients.json

---

data/clients.json

[Step CLI](https://github.com/smallstep/cli) is an ACME v2 client.

Add Step CLI to clients.json

---

data/clients.json

This repo doesn't seem to be maintained anymore, and should therefore be removed.

Unmaintained repo

---

data/clients.json

Add acme-redirect to clients.json

---

content/es/getting-started.md

typo in "inactividad"

---

config/_default/menu.es.toml

Cf https://community.letsencrypt.org/t/solutions-in-french-portuguese-help-threads/142210/29

Link to the new category ayuda-en-espanol in the forum

---

content/en/docs/challenge-types.md

Fix "whether and update" to "whether an update"

---

content/en/about.md

Add link to RFC8555

---

content/fr/docs/caa.md

typo fix: "nomé' -> "nommé"

---

TRANSLATION.md

Update translation instructions to point to Crowndin

---

data/clients.json

Fix ansible acme_certificate module URL

---

content/es/about.md

cambio en palabra de la traduccion a español

---

content/en/docs/staging-environment.md

Add more details on the staging hierarchy including the wide
availability of ECDSA intermediates and how boulder handles
ECDSA end-entity certificates.

Update the Staging Environment Page for ECDSA issuance

---

content/en/certificates.md

Update Information about Root X2

---

content/en/docs/dst-root-ca-x3-expiration-september-2021.md

Fix compatibility link.

---

content/en/certificates.md

publicly available good
pubicly available not so good

Fixed unfortunate typo

---

data/clients.json

Just recently re-added HTTP-01 and TLS-ALPN-01, so just updating that
here!

data/clients.json: Update Terraform provider challenges

---

content/en/certificates.md
content/en/upcoming-features.md

+ Updates about the ECSDSA hierarchy roots and
intermediate availability and link to the community forum for more
information
+ Update information about cross-sinatures to include Root X2
signed by Root X1

Prod ecdsa allowlist

---

content/en/docs/cert-compat.md

This clarifies a misunderstanding I saw someone have on the forum.

Add note about Android compatibility.

---

data/clients.json

Add gitlab to the list of projects.

Add gitlab

---

layouts/partials/footer.html
layouts/partials/header.html
layouts/partials/hero.html
src/js/main.js

Fixes https://github.com/letsencrypt/cp-cps/issues/57

Suppress header & footer for documents section

---

content/zh-tw/how-it-works.md

Usually we use the term "運作原理" instead of "工作原理" in Taiwan.

Update the translation for "How It Works" in zh-tw

---

content/zh-cn/upcoming-features.md

translate zh-cn for May 03, 2021 upcoming-features

---

content/es/docs/dst-root-ca-x3-expiration-september-2021.md

Translate the page into Spanish

Update [es] dst-root-ca-x3-expiration-september-2021.md

---

content/en/docs/faq.md

Based on https://github.com/letsencrypt/website/pull/1186 (English only)

Add link to challenge types in wildcard QA

---

content/zh-cn/docs/dst-root-ca-x3-expiration-september-2021.md

Add Chinese translation of the article "DST Root CA X3 Expiration (September 2021)"

Add Chinese translation of an article

---

layouts/shortcodes/clients.html
src/css/_base.scss

List Client options page in Hebrew should be LTRed 

---

.github/workflows/test.yaml
config/_default/config.toml
layouts/index.html
layouts/partials/lastmod.html
layouts/post/single.html
layouts/shortcodes/clientslastmod.html
netlify.toml
static/js/i18n.js

Update to Hugo 0.88.1
Use Hugo new date formating to handle dates in languages other than English (was done using javascript before): https://gohugo.io/news/0.87.0-relnotes/

[WIP] Hugo_v0.88.1

---

.github/workflows/test.yaml
.htmlhintrc
package-lock.json
package.json

Update CI checks (node and npm package versions), and html hint tests.

Update tools and checks

---

.gitignore
src/css/_layout.scss

Equalized the top/bottom padding for the donate box.
Before:
After:

Issue 1319

---

config/_default/languages.it.toml
config/_default/menu.it.toml

Fix issues with Italian translation's appearance and add a menu file

Update and add Italian translation files

---

config/_default/menu.id.toml

Added Become a Sponsor to Indonesian dropdown menu

Update Indonesian Translation

---

content/en/tlsalpnrevocation.md

This should help the less technical folks out there.

Add TLS-ALPN-01 incident web tool to investigate data set

---

content/en/docs/a-warm-welcome-to-asn1-and-der.md

Warm Welcome: Update link for serial entropy

---

data/clients.json

Add Az-Acme to the list of clients

Add Az-Acme

---

content/en/post/2022-05-19-nurturing-ct-log-growth.md

This adds TrustAsia per [Andrew Ayer on Twitter](https://twitter.com/__agwa/status/1527407151660122114)

Update Oak Update 2022 post, per Andrew Ayer's correction on Twitter

---

content/en/docs/cert-compat.md
content/en/docs/glossary.md

Fix cert compat grammar error ("check our our website" 🙃) and update files to include more relevant OS/browsers.

Update grammar and file relevancy

---

config/_default/config.toml

Turning off the fundraiser option on the donate page

Turn off Fundraiser

---

content/en/docs/expiration-emails.md

Fix spelling mistake in en/docs/expiration-emails.md

---

layouts/shortcodes/fundraiser.html

Change Product Order

---

content/en/docs/client-options.md
content/en/docs/faq.md

- Add a FAQ for why we ask for randomness in renewal times
- Add a criteria to the client list for future clients to use randomness in their renewal times, linking to the integration guide.

Add more requests for routine renewals to occur at randomized times

---

content/en/post/2022-12-15-OCSPcaching.md

Note: Change date to 12-15 when finished

New Blog Post: Let’s Encrypt improves how we manage OCSP response

---

content/en/contact.md

Update Newsletter Link

---

content/da/contact.md
content/de/contact.md
content/en/contact.md
content/en/post/2021-10-01-cert-chaining-help.md
content/fi/contact.md
content/fr/contact.md
content/he/contact.md
content/hu/contact.md
content/id/contact.md
content/it/contact.md
content/ja/contact.md
content/ko/contact.md
content/pt-br/contact.md
content/ru/contact.md
content/si/contact.md
content/sv/contact.md
content/uk/contact.md
content/vi/contact.md
content/zh-cn/contact.md

The newsletter has been moved from mailchimp to pardot. Updating the URLs pointing to it.

Newsletter change Feb 2023

---

layouts/shortcodes/elevate_form.html

Temporary fix while static.elevate.salesforce.org has an invalid SSL cert.

Temporarily replace Donate form with Button

---

static/.well-known/security.txt

Add missing URI syntax to security.txt Contact field

---

content/en/osn-event.html

Add Language to OSN

---

content/da/docs/rate-limits.md
content/de/docs/rate-limits.md
content/en/docs/rate-limits.md
content/es/docs/rate-limits.md
content/fr/docs/rate-limits.md
content/he/docs/rate-limits.md
content/hu/docs/rate-limits.md
content/ja/docs/rate-limits.md
content/ko/docs/rate-limits.md
content/pt-br/docs/rate-limits.md
content/ru/docs/rate-limits.md
content/sv/docs/rate-limits.md
content/uk/docs/rate-limits.md
content/zh-cn/docs/rate-limits.md
content/zh-tw/docs/rate-limits.md

The links were updated in all translated languages.

Revert all lastmods from #1534, as only links were changed

---

content/en/upcoming-features.md
content/es/upcoming-features.md

Move ARI to Completed Features in en/es versions of upcoming-features.md

---

static/.well-known/security.txt

Add fields to security.txt

---

content/en/post/2023-03-23-improving-resliiency-and-reliability-with-ARI.md

Adjust's "Let's Encrypted" to "Let's Encrypt"

[minor] fix typo in blog post

---

content/en/docs/ct-logs.html
data/transparency.json

Update CT shard details

---

data/clients.json

Add Proxmox VE as integrating project

add proxmox ve to list of integrating projects

---

content/en/docs/cert-compat.md

We're about to add more abilities to use Root X2 as a trust anchor, so let's do some minor revisions here and help people find what they need to know.

Update Certificate Compatibility to reference new Forum Post.

---

i18n/ta.toml

Fix layout in Tamil on the main page

Fix layout in Tamil

---

content/it/contact.md

Relates to https://github.com/letsencrypt/website/pull/1572

Fix contacts in Italian

---

content/he/contact.md

Fix he contact page

---

content/ca/getting-started.md

The latest "Getting started" in Catalan from Crowdin.

Add getting started in Catalan

---

content/pt-br/docs/failed-validation-limit.md

Update in pt-br/docs/failed-validation-limit.md
See:
https://github.com/letsencrypt/website/pull/1589#issuecomment-1783435177

update in pt-br/docs/failed-validation-limit.md

---

content/da/certificates.md
content/da/contact.md
content/da/docs/account-id.md
content/da/docs/caa.md
content/da/docs/cert-compat.md
content/da/docs/ct-logs.html
content/da/docs/dst-root-ca-x3-expiration-september-2021.md
content/da/stats-dashboard.html
content/da/thankyou.html
i18n/da.toml

Add DA translations

---

content/da/trademarks.md
content/da/upcoming-features.md

The latest Danish translations from Crowdin

Danish translations

---

content/en/repository.html

Update links to 2023 Webtrust audit reports to use CPA Canada seals.

Update repository to include 2023 WebTrust seals

---

TRANSLATION.md
content/da/docs/faq.md
content/da/docs/too-many-registrations-for-this-ip.md
content/da/how-it-works.md
content/da/privacy.md
content/da/stats.html
content/pl/docs/staging-environment.md
content/pl/stats-dashboard.html
content/pl/stats.html
content/zh-cn/about.md
content/zh-cn/contact.md
content/zh-cn/docs/account-id.md
content/zh-cn/docs/cert-compat.md
content/zh-cn/docs/certificates-for-localhost.md
content/zh-cn/docs/client-options.md
content/zh-cn/docs/godaddy.md
content/zh-cn/getinvolved.md
content/zh-cn/getting-started.md
content/zh-cn/sponsors.html
i18n/da.toml
i18n/he.toml
i18n/pl.toml

- New PL, ZH-CN and DA translations
- An update in TRANSLATION.md.

new PL, ZH-CN and DA translations

---

content/he/getting-started.md
content/he/thankyou.md
content/zh-cn/docs/glossary.md
content/zh-cn/donate.html

Latest HE and ZH-CN translations from Crowdin.

Latest HE and ZH-CN translations

---

content/zh-cn/docs/glossary.md

Latest ZH-CN translations from Crowdin

Latest ZH-CN translations

---

content/en/post/2023-07-10-cross-sign-expiration.md

We have completed the Feb 08 step, so change tense to note that.

Update transition timeline to note first stage complete

---

content/de/docs/dst-root-ca-x3-expiration-september-2021.md

The latest German and Sinhala translations from Crowdin. Updates in Crowdin in both, resulted in one changed file in German though.

The latest DE and SI translations

---

content/sv/docs/allow-port-80.md
content/sv/getinvolved.md

Updates in Swedish translations.

New SE translations

---

content/fr/about.md
content/fr/contact.md
content/fr/docs/a-warm-welcome-to-asn1-and-der.md
content/fr/docs/godaddy.md
content/fr/getinvolved.md
content/fr/sponsors.html

The latest FR translations from Crowdin

New FR translations

---

content/en/docs/ct-logs.html
data/transparency.json
layouts/shortcodes/ct_logs.html

This adds a new section titled "Sunlight" which isn't localized as it is a proper name.

Add Sunlight logs to the ct-logs page

---

content/da/donate.html
content/he/docs/dst-root-ca-x3-expiration-september-2021.md
content/it/donate.html
content/zh-cn/donate.html

Latest Danish, Hebrew, Italian and Chinese Simplified translations from Crowdin.

New DA, HE, IT, ZH-CN translations

---

content/cs/how-it-works.md
content/zh-cn/docs/staging-environment.md
content/zh-cn/donate.html

- updates in Chinese (China), Czech

Updates in ZH-CN, CS

---

content/uk/docs/cert-compat.md

New UK translations

---

content/cs/trademarks.md
content/da/certificates.md
content/da/docs/dst-root-ca-x3-expiration-september-2021.md

- Updates in Danish and Czech translations

New DA, CS translations

---

content/cs/privacy.md

Update in CS

---

content/en/docs/faq.md
content/en/how-it-works.md
content/en/privacy.md

Stemming from discussion in https://github.com/letsencrypt/website/issues/1694, publicize our use of CT and RVA in various documents.

Broadly mention CT and RVA use

---

content/cs/donate.html
content/cs/donation-information.html
content/cs/privacy.md
content/da/donate.html
i18n/cs.toml
i18n/da.toml

Udpates in DA,CS

---

content/da/docs/cert-compat.md
content/he/donate.html
content/zh-cn/docs/cert-compat.md
content/zh-cn/donate.html
i18n/zh-cn.toml

- Updates in Danish, Hebrew, Chinese (China). 
- Updates in the source file: `content/en/donate.html` https://github.com/letsencrypt/website/pull/1728/

Updates in DA,HE,ZH-CN, updates in donate.html

---

content/cs/upcoming-features.md
content/he/docs/cert-compat.md

Updates in CS, HE

---

content/zh-cn/docs/glossary.md

Update in zh-CN

---

config/_default/languages.ca.toml
config/_default/languages.el.toml
config/_default/languages.en.toml
config/_default/languages.pl.toml
config/_default/languages.ta.toml
config/_default/languages.th.toml

Resolves warnings in hugo build and fixes compatibility with future versions of Hugo.

Fix language parameters for some languages.

---

layouts/partials/head.html

Fix 1: The missing comma in the meta viewport tag can cause problems in some browsers or lead to inconsistent behavior, especially on mobile devices.
Fix 2: For performance optimization lets preload critical assets like CSS files.
Fix 3: Improved SEO with Open Graph Tags

head optimization

---

config/_default/languages.sv.toml
config/_default/languages.zh-cn.toml

- Update in Swedish: `_default/languages.sv.toml`
- Fix the parameter `weight` 
- Update in  Chinese (China): `_default/languages.zh-cn-toml`
- Fix the Paypal link

Updates in SV,ZH-CN

---

config/_default/languages.de.toml
config/_default/menu.de.toml
content/de/docs/ct-logs.html
content/de/docs/dst-root-ca-x3-expiration-september-2021.md
content/de/docs/faq.md
content/de/docs/glossary.md
content/de/donate.html
content/de/how-it-works.md
content/de/upcoming-features.md
content/he/certificates.md
i18n/de.toml

- Updates in German and Hebrew

Updates in DE,HE

---

content/cs/donate.html
content/da/donate.html
content/de/donate.html
content/he/donate.html
content/ru/donate.html
content/zh-cn/donate.html

- Relates to https://github.com/letsencrypt/website/pull/1769

Update translations in /content/donate.html

---

config/_default/languages.pl.toml

Update in PL

---

content/es/getinvolved.md
content/fi/getinvolved.md
content/hu/getinvolved.md
content/id/getinvolved.md
content/si/getinvolved.md
content/sr/getinvolved.md

Small PR - Commit https://github.com/letsencrypt/boulder/commit/b3c56a5d05992b3e1a8e7d36930cc41aaff9b803 moved `CONTRIBUTING.md`. This PR adjusts sources to changes.

Update Boulder contribution guide reference

---

content/en/docs/rate-limits.md

Fixes a typo in the docs, thanks @b9a1!
Fixes #1796

Off by one error in unpausing doc

---

config/_default/languages.he.toml
content/da/about.md
content/da/docs/rate-limits.md

- Updates in Danish, Hebrew
The update in Danish also relates to https://github.com/letsencrypt/website/pull/1799

Updates in DA,HE

---

content/en/docs/challenge-types.md

- Indicate which challenge types can be used for ipAddress SANs
- Move TLS-SNI-01 to the bottom
- Fix markdown lint issues

Update 'Challenge Types' documentation page

---

content/en/documents/ISRG-CP-CPS-v5.7.html
content/en/repository.html

CP/CPS v5.7

---

content/he/docs/client-options.md
content/he/docs/monitoring-options.md
content/zh-cn/docs/client-options.md
content/zh-cn/docs/monitoring-options.md

- Updated translations in Hebrew, Chinese (China)

Updates in HE,ZH-CN

---

content/en/docs/revoking.md

Clarify instructions for avoiding issuance while revoking from a different account

---

data/clients.json

This was duplicated on ln 599/594

Remove dupe Acme PHP link clients.json

---

content/tr/contact.md
content/tr/docs/expiration-emails.md

Updates in TR

---

content/en/repository.html

To be merged on February 24 when v1.5 Subscriber Agreement becomes effective.

Update upcoming/currently effective wording for SA agreement

---

config/_default/menu.cs.toml
content/da/docs/expiration-emails.md
content/da/docs/profiles.md
content/zh-cn/docs/expiration-emails.md

- Updates in Czech, Danish, Chinese (China)

Updates in CS,DA,ZH-CN

---

config/_default/languages.pt-br.toml
config/_default/menu.pt-br.toml
i18n/he.toml

- Updates in Hebrew and Portuguese Brazil

Updates in HE,PT-BR

---

config/_default/menu.da.toml
config/_default/menu.tr.toml
content/da/docs/glossary.md
content/da/docs/staging-environment.md
content/tr/about.md
content/tr/getinvolved.md
content/tr/stats-dashboard.html
content/tr/stats.html
content/tr/thankyou.md
content/tr/trademarks.md
content/zh-cn/docs/staging-environment.md
i18n/da.toml
i18n/tr.toml

- Updates in Chinese (China), Danish, Portuguese Brazilian and Turkish.

Updates in DA,PT-BR,TR,ZH-CN

---

config/_default/menu.fr.toml
content/fr/docs/monitoring-options.md
content/fr/donate.html
i18n/fr.toml

Updates in FR

---

content/en/docs/profiles.md

Add max names to profiles page

---

config/_default/menu.zh-tw.toml
i18n/zh-tw.toml

Updates in ZH-TW

---

static/.well-known/security.txt

Remove Encryption link from security.txt

---

config/_default/menu.ru.toml
i18n/cs.toml
i18n/da.toml
i18n/zh-cn.toml

- Updates in Czech, Danish, Russian and Chinese (China)

Updates in CS,DA,RU,ZH-CN

---

content/cs/donate.html
content/da/donate.html
content/zh-cn/donate.html
i18n/he.toml

- Fix `donate.html` page in Czech, Danish, Chinese (China)
- Updates in Hebrew

Fix donate.html page in CS,DA,ZH-CN

---

content/en/upcoming-features.md

Clean out very old features, add some recent accomplishments, and list various high-profile changes that we've announced are coming in the next year or so.
---
> [!WARNING]
> Do not merge before https://github.com/letsencrypt/website/pull/1911

Update "Upcoming Features" page

---

content/he/certificates.md
content/he/donate.html
i18n/he.toml

Updates in HE

---

content/cs/upcoming-features.md
content/zh-cn/docs/staging-environment.md
content/zh-cn/upcoming-features.md

- Updates in Czech, Chinese (China)

Updates in CS,ZH-CN

---

content/en/post/2025-07-01-issuing-our-first-ip-address-certificate.md

Blog: We've Issued Our First IP Address Certificate

---

data/clients.json

* Added the Pulumi ACME provider to the list of configuration management tools
* Sorted the entries alphabetically

Add Pulumi ACME provider & sort config mgmt tools alphabetically

---

content/en/how-it-works.md

I spelled out a few terms that newcomers may not know and added links where people can find more information.

Clarify terms and add links to "How It Works" article

---

content/en/getinvolved.md

* Reorder sections to reflect contribution priorities
* Make things more concise

Improve Get Involved page.

---

content/en/docs/certificates-for-localhost.md

Resolves #1060 
Translations get updated via Crowdin.

Suggest mkcert over minica.

---

content/de/docs/expiration-emails.md

Updates in DE

---

i18n/en.toml
themes/le-2025/layouts/_default/single.html
themes/le-2025/layouts/partials/components/post-hero.html

Let people know if fresher English language content is available

---

i18n/en.toml

Direct translation contributors to Crowdin rather than GitHub

---

.github/workflows/test.yaml
DOCUMENTATION.md
netlify.toml

This PR bumps hugo to latest released version 0.148.2.

Bump hugo to latest released version 0.148.2

---

content/en/docs/godaddy.md

* Improve wording
* Add reference to CertSage (@GriffinSoftware)

Update godaddy docs page.

---

netlify.toml

Ensure they take priority over page content

Add force=true to cp/cps redirects

---

config/_default/menu.de.toml
config/_default/menu.pl.toml
content/da/docs/client-options.md
content/da/docs/ct-logs.html
content/de/certificates.md
content/de/docs/account-id.md
content/de/docs/allow-port-80.md
content/de/docs/ipv6.md
content/de/docs/lencr-org.md
content/de/donate.html
content/de/stats-dashboard.html
content/de/thankyou.md
content/de/upcoming-features.md
content/pl/stats-dashboard.html

- Updates in Danish, German and Polish
- Push latest Certificates page in German https://github.com/letsencrypt/website/pull/1658#issuecomment-3244330618

Updates in DA,DE,PL

---

content/zh-cn/certificates.md

Updates in ZH-CN

---

i18n/en.toml
package-lock.json
package.json
themes/le-2025/assets/js/number-animation.js

Also fixes eslint error related to quoting in these files.

Update number of websites
